version: '2.4'
services:
    vanetza:
        hostname: vanetza
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        volumes:
          - ./config.ini:/config.ini
          - /services/info.ini:/info.ini
        cap_add:
            - "NET_ADMIN"
        environment:
            - START_EMBEDDED_MOSQUITTO=false
            - SUPPORT_MAC_BLOCKING=false
        network_mode: "host" 
        ipc: shareable
        shm_size: 300M