/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Description"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#include "CAM-PDU-Description_SafetyCarContainer.h"

asn_TYPE_member_t asn_MBR_CAM_PDU_Description_SafetyCarContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CAM_PDU_Description_SafetyCarContainer, lightBarSirenInUse),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ETSI_ITS_CDD_LightBarSirenInUse,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"lightBarSirenInUse"
		},
	{ ATF_POINTER, 3, offsetof(struct CAM_PDU_Description_SafetyCarContainer, incidentIndication),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CauseCodeV2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"incidentIndication"
		},
	{ ATF_POINTER, 2, offsetof(struct CAM_PDU_Description_SafetyCarContainer, trafficRule),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ETSI_ITS_CDD_TrafficRule,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"trafficRule"
		},
	{ ATF_POINTER, 1, offsetof(struct CAM_PDU_Description_SafetyCarContainer, speedLimit),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ETSI_ITS_CDD_SpeedLimit,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"speedLimit"
		},
};
static const int asn_MAP_CAM_PDU_Description_SafetyCarContainer_oms_1[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_CAM_PDU_Description_SafetyCarContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CAM_PDU_Description_SafetyCarContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lightBarSirenInUse */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* incidentIndication */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* trafficRule */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* speedLimit */
};
asn_SEQUENCE_specifics_t asn_SPC_CAM_PDU_Description_SafetyCarContainer_specs_1 = {
	sizeof(struct CAM_PDU_Description_SafetyCarContainer),
	offsetof(struct CAM_PDU_Description_SafetyCarContainer, _asn_ctx),
	asn_MAP_CAM_PDU_Description_SafetyCarContainer_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_CAM_PDU_Description_SafetyCarContainer_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CAM_PDU_Description_SafetyCarContainer = {
	"SafetyCarContainer",
	"SafetyCarContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_CAM_PDU_Description_SafetyCarContainer_tags_1,
	sizeof(asn_DEF_CAM_PDU_Description_SafetyCarContainer_tags_1)
		/sizeof(asn_DEF_CAM_PDU_Description_SafetyCarContainer_tags_1[0]), /* 1 */
	asn_DEF_CAM_PDU_Description_SafetyCarContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_CAM_PDU_Description_SafetyCarContainer_tags_1)
		/sizeof(asn_DEF_CAM_PDU_Description_SafetyCarContainer_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_CAM_PDU_Description_SafetyCarContainer_1,
	4,	/* Elements count */
	&asn_SPC_CAM_PDU_Description_SafetyCarContainer_specs_1	/* Additional specs */
};

