/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Description"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_CyclistTypeSpecificInformation_H_
#define	_CyclistTypeSpecificInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_VruSubProfileBicyclist.h"
#include "ETSI-ITS-CDD_VruMovementControl.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CyclistTypeSpecificInformation */
typedef struct CyclistTypeSpecificInformation {
	ETSI_ITS_CDD_VruSubProfileBicyclist_t	*vruSubProfileBicyclist;	/* OPTIONAL */
	ETSI_ITS_CDD_VruMovementControl_t	*vruMovementControl;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CyclistTypeSpecificInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CyclistTypeSpecificInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_CyclistTypeSpecificInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_CyclistTypeSpecificInformation_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CyclistTypeSpecificInformation_H_ */
#include "asn_internal.h"
