/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "asn1/EN302637-3v131-DENM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_DENM_PDU_Descriptions_LocationContainer_H_
#define	_DENM_PDU_Descriptions_LocationContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ITS-Container_Traces.h"
#include "ITS-Container_RoadType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ITS_Container_Speed;
struct ITS_Container_Heading;

/* DENM-PDU-Descriptions_LocationContainer */
typedef struct DENM_PDU_Descriptions_LocationContainer {
	struct ITS_Container_Speed	*eventSpeed;	/* OPTIONAL */
	struct ITS_Container_Heading	*eventPositionHeading;	/* OPTIONAL */
	ITS_Container_Traces_t	 traces;
	ITS_Container_RoadType_t	*roadType;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DENM_PDU_Descriptions_LocationContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DENM_PDU_Descriptions_LocationContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_DENM_PDU_Descriptions_LocationContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_DENM_PDU_Descriptions_LocationContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ITS-Container_Speed.h"
#include "ITS-Container_Heading.h"

#endif	/* _DENM_PDU_Descriptions_LocationContainer_H_ */
#include "asn_internal.h"
