/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Description"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_EHorizonLocationSharingContainer_H_
#define	_EHorizonLocationSharingContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_PolygonalLine.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ConfidenceLevels;
struct BasicLaneConfiguration;
struct MetaInformation;

/* EHorizonLocationSharingContainer */
typedef struct EHorizonLocationSharingContainer {
	ETSI_ITS_CDD_PolygonalLine_t	 segmentAhead;
	struct ConfidenceLevels	*nodeProbabilities;	/* OPTIONAL */
	ETSI_ITS_CDD_PolygonalLine_t	 segmentBehind;
	struct BasicLaneConfiguration	*laneLevelDetails;	/* OPTIONAL */
	struct MetaInformation	*segmentSource;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EHorizonLocationSharingContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EHorizonLocationSharingContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_EHorizonLocationSharingContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_EHorizonLocationSharingContainer_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ConfidenceLevels.h"
#include "BasicLaneConfiguration.h"
#include "MetaInformation.h"

#endif	/* _EHorizonLocationSharingContainer_H_ */
#include "asn_internal.h"
