/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "iso/CDD-Release2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_VruProfileAndSubprofile_H_
#define	_ETSI_ITS_CDD_VruProfileAndSubprofile_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_VruSubProfilePedestrian.h"
#include "ETSI-ITS-CDD_VruSubProfileBicyclist.h"
#include "ETSI-ITS-CDD_VruSubProfileMotorcyclist.h"
#include "ETSI-ITS-CDD_VruSubProfileAnimal.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ETSI_ITS_CDD_VruProfileAndSubprofile_PR {
	ETSI_ITS_CDD_VruProfileAndSubprofile_PR_NOTHING,	/* No components present */
	ETSI_ITS_CDD_VruProfileAndSubprofile_PR_pedestrian,
	ETSI_ITS_CDD_VruProfileAndSubprofile_PR_bicyclistAndLightVruVehicle,
	ETSI_ITS_CDD_VruProfileAndSubprofile_PR_motorcyclist,
	ETSI_ITS_CDD_VruProfileAndSubprofile_PR_animal
	/* Extensions may appear below */
	
} ETSI_ITS_CDD_VruProfileAndSubprofile_PR;

/* ETSI-ITS-CDD_VruProfileAndSubprofile */
typedef struct ETSI_ITS_CDD_VruProfileAndSubprofile {
	ETSI_ITS_CDD_VruProfileAndSubprofile_PR present;
	union ETSI_ITS_CDD_VruProfileAndSubprofile_u {
		ETSI_ITS_CDD_VruSubProfilePedestrian_t	 pedestrian;
		ETSI_ITS_CDD_VruSubProfileBicyclist_t	 bicyclistAndLightVruVehicle;
		ETSI_ITS_CDD_VruSubProfileMotorcyclist_t	 motorcyclist;
		ETSI_ITS_CDD_VruSubProfileAnimal_t	 animal;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ETSI_ITS_CDD_VruProfileAndSubprofile_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_VruProfileAndSubprofile;
extern asn_CHOICE_specifics_t asn_SPC_ETSI_ITS_CDD_VruProfileAndSubprofile_specs_1;
extern asn_TYPE_member_t asn_MBR_ETSI_ITS_CDD_VruProfileAndSubprofile_1[4];
extern asn_per_constraints_t asn_PER_type_ETSI_ITS_CDD_VruProfileAndSubprofile_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_VruProfileAndSubprofile_H_ */
#include "asn_internal.h"
