/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EV-RechargingSpotReservation-PDU-Descriptions"
 * 	found in "asn1/EV-RSR-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_EV_RSR_H_
#define	_EV_RSR_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ITS-Container_ItsPduHeader.h"
#include "EV-RSR-MessageBody.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EV-RSR */
typedef struct EV_RSR {
	ITS_Container_ItsPduHeader_t	 header;
	EV_RSR_MessageBody_t	 messageBody;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EV_RSR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EV_RSR;

#ifdef __cplusplus
}
#endif

#endif	/* _EV_RSR_H_ */
#include "asn_internal.h"
