/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "iso/ISO19321.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_IVI_RoadConfigurationContainer_H_
#define	_IVI_RoadConfigurationContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RccPart;

/* IVI_RoadConfigurationContainer */
typedef struct IVI_RoadConfigurationContainer {
	A_SEQUENCE_OF(struct RccPart) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IVI_RoadConfigurationContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IVI_RoadConfigurationContainer;
extern asn_SET_OF_specifics_t asn_SPC_IVI_RoadConfigurationContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_IVI_RoadConfigurationContainer_1[1];
extern asn_per_constraints_t asn_PER_type_IVI_RoadConfigurationContainer_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RccPart.h"

#endif	/* _IVI_RoadConfigurationContainer_H_ */
#include "asn_internal.h"
