/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "iso/CDD-Release2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ParkingAreaArrangementType_H_
#define	_ParkingAreaArrangementType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParkingAreaArrangementType {
	ParkingAreaArrangementType_parallelParkingSpace	= 0,
	ParkingAreaArrangementType_diagonalParkingSpace	= 1,
	ParkingAreaArrangementType_perpendicularParkingSpace	= 2,
	ParkingAreaArrangementType_queueParking	= 3,
	ParkingAreaArrangementType_mixed	= 4,
	ParkingAreaArrangementType_unknown	= 7
} e_ParkingAreaArrangementType;

/* ParkingAreaArrangementType */
typedef long	 ParkingAreaArrangementType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ParkingAreaArrangementType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ParkingAreaArrangementType;
asn_struct_free_f ParkingAreaArrangementType_free;
asn_struct_print_f ParkingAreaArrangementType_print;
asn_constr_check_f ParkingAreaArrangementType_constraint;
ber_type_decoder_f ParkingAreaArrangementType_decode_ber;
der_type_encoder_f ParkingAreaArrangementType_encode_der;
xer_type_decoder_f ParkingAreaArrangementType_decode_xer;
xer_type_encoder_f ParkingAreaArrangementType_encode_xer;
jer_type_encoder_f ParkingAreaArrangementType_encode_jer;
oer_type_decoder_f ParkingAreaArrangementType_decode_oer;
oer_type_encoder_f ParkingAreaArrangementType_encode_oer;
per_type_decoder_f ParkingAreaArrangementType_decode_uper;
per_type_encoder_f ParkingAreaArrangementType_encode_uper;
per_type_decoder_f ParkingAreaArrangementType_decode_aper;
per_type_encoder_f ParkingAreaArrangementType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ParkingAreaArrangementType_H_ */
#include "asn_internal.h"
