/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TIS-TPG-Transactions-Descriptions"
 * 	found in "asn1/TIS-TPG-Transactions-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_PlacardTable_H_
#define	_PlacardTable_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TyreSetVariant;

/* PlacardTable */
typedef struct PlacardTable {
	A_SEQUENCE_OF(struct TyreSetVariant) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PlacardTable_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PlacardTable;
extern asn_SET_OF_specifics_t asn_SPC_PlacardTable_specs_1;
extern asn_TYPE_member_t asn_MBR_PlacardTable_1[1];
extern asn_per_constraints_t asn_PER_type_PlacardTable_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TyreSetVariant.h"

#endif	/* _PlacardTable_H_ */
#include "asn_internal.h"
