/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Description"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_TwoWheelerContainer_H_
#define	_TwoWheelerContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TwoWheelerTypeSpecificInformation;
struct CartesianAngle;
struct Wgs84Angle;
struct ETSI_ITS_CDD_StabilityChangeIndication;

/* TwoWheelerContainer */
typedef struct TwoWheelerContainer {
	struct TwoWheelerTypeSpecificInformation	*typeSpecificInformation;	/* OPTIONAL */
	struct CartesianAngle	*rollAngle;	/* OPTIONAL */
	struct Wgs84Angle	*orientation;	/* OPTIONAL */
	struct ETSI_ITS_CDD_StabilityChangeIndication	*stabilityChangeIndication;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TwoWheelerContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TwoWheelerContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_TwoWheelerContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_TwoWheelerContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TwoWheelerTypeSpecificInformation.h"
#include "CartesianAngle.h"
#include "Wgs84Angle.h"
#include "ETSI-ITS-CDD_StabilityChangeIndication.h"

#endif	/* _TwoWheelerContainer_H_ */
#include "asn_internal.h"
