/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VAM_PDU_Descriptions_MapPosition_H_
#define	_VAM_PDU_Descriptions_MapPosition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IntersectionReferenceID.h"
#include "LaneID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VAM-PDU-Descriptions_MapPosition */
typedef struct VAM_PDU_Descriptions_MapPosition {
	IntersectionReferenceID_t	 intersectionId;
	LaneID_t	 lane;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VAM_PDU_Descriptions_MapPosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VAM_PDU_Descriptions_MapPosition;
extern asn_SEQUENCE_specifics_t asn_SPC_VAM_PDU_Descriptions_MapPosition_specs_1;
extern asn_TYPE_member_t asn_MBR_VAM_PDU_Descriptions_MapPosition_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _VAM_PDU_Descriptions_MapPosition_H_ */
#include "asn_internal.h"
