/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VAM_PDU_Descriptions_VruSubProfileBicyclist_H_
#define	_VAM_PDU_Descriptions_VruSubProfileBicyclist_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VAM_PDU_Descriptions_VruSubProfileBicyclist {
	VAM_PDU_Descriptions_VruSubProfileBicyclist_unavailable	= 0,
	VAM_PDU_Descriptions_VruSubProfileBicyclist_bicyclist	= 1,
	VAM_PDU_Descriptions_VruSubProfileBicyclist_wheelchair_user	= 2,
	VAM_PDU_Descriptions_VruSubProfileBicyclist_horse_and_rider	= 3,
	VAM_PDU_Descriptions_VruSubProfileBicyclist_rollerskater	= 4,
	VAM_PDU_Descriptions_VruSubProfileBicyclist_e_scooter	= 5,
	VAM_PDU_Descriptions_VruSubProfileBicyclist_personal_transporter	= 6,
	VAM_PDU_Descriptions_VruSubProfileBicyclist_pedelec	= 7,
	VAM_PDU_Descriptions_VruSubProfileBicyclist_speed_pedelec	= 8,
	VAM_PDU_Descriptions_VruSubProfileBicyclist_max	= 15
} e_VAM_PDU_Descriptions_VruSubProfileBicyclist;

/* VAM-PDU-Descriptions_VruSubProfileBicyclist */
typedef long	 VAM_PDU_Descriptions_VruSubProfileBicyclist_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VAM_PDU_Descriptions_VruSubProfileBicyclist_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VAM_PDU_Descriptions_VruSubProfileBicyclist;
extern const asn_INTEGER_specifics_t asn_SPC_VAM_PDU_Descriptions_VruSubProfileBicyclist_specs_1;
asn_struct_free_f VAM_PDU_Descriptions_VruSubProfileBicyclist_free;
asn_struct_print_f VAM_PDU_Descriptions_VruSubProfileBicyclist_print;
asn_constr_check_f VAM_PDU_Descriptions_VruSubProfileBicyclist_constraint;
ber_type_decoder_f VAM_PDU_Descriptions_VruSubProfileBicyclist_decode_ber;
der_type_encoder_f VAM_PDU_Descriptions_VruSubProfileBicyclist_encode_der;
xer_type_decoder_f VAM_PDU_Descriptions_VruSubProfileBicyclist_decode_xer;
xer_type_encoder_f VAM_PDU_Descriptions_VruSubProfileBicyclist_encode_xer;
jer_type_encoder_f VAM_PDU_Descriptions_VruSubProfileBicyclist_encode_jer;
oer_type_decoder_f VAM_PDU_Descriptions_VruSubProfileBicyclist_decode_oer;
oer_type_encoder_f VAM_PDU_Descriptions_VruSubProfileBicyclist_encode_oer;
per_type_decoder_f VAM_PDU_Descriptions_VruSubProfileBicyclist_decode_uper;
per_type_encoder_f VAM_PDU_Descriptions_VruSubProfileBicyclist_encode_uper;
per_type_decoder_f VAM_PDU_Descriptions_VruSubProfileBicyclist_decode_aper;
per_type_encoder_f VAM_PDU_Descriptions_VruSubProfileBicyclist_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VAM_PDU_Descriptions_VruSubProfileBicyclist_H_ */
#include "asn_internal.h"
