/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "iso/CDD-Release2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VehicleMovementControl_H_
#define	_VehicleMovementControl_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PedalStatus.h"
#include "ETSI-ITS-CDD_SaeAutomationLevel.h"
#include "AutomationControl.h"
#include "ETSI-ITS-CDD_AccelerationControl.h"
#include "AccelerationControlExtension.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleMovementControl */
typedef struct VehicleMovementControl {
	PedalStatus_t	 accelerationPedalStatus;
	PedalStatus_t	 brakePedalStatus;
	ETSI_ITS_CDD_SaeAutomationLevel_t	*saeAutomationLevel;	/* OPTIONAL */
	AutomationControl_t	*automationControl;	/* OPTIONAL */
	ETSI_ITS_CDD_AccelerationControl_t	*accelerationControl;	/* OPTIONAL */
	AccelerationControlExtension_t	*accelerationControlExtension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleMovementControl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleMovementControl;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleMovementControl_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleMovementControl_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleMovementControl_H_ */
#include "asn_internal.h"
