/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "iso/CDD-Release2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VehicleHeight2_H_
#define	_VehicleHeight2_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleHeight2 {
	VehicleHeight2_outOfRange	= 61,
	VehicleHeight2_unavailable	= 62
} e_VehicleHeight2;

/* VehicleHeight2 */
typedef long	 VehicleHeight2_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehicleHeight2_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehicleHeight2;
asn_struct_free_f VehicleHeight2_free;
asn_struct_print_f VehicleHeight2_print;
asn_constr_check_f VehicleHeight2_constraint;
ber_type_decoder_f VehicleHeight2_decode_ber;
der_type_encoder_f VehicleHeight2_encode_der;
xer_type_decoder_f VehicleHeight2_decode_xer;
xer_type_encoder_f VehicleHeight2_encode_xer;
jer_type_encoder_f VehicleHeight2_encode_jer;
oer_type_decoder_f VehicleHeight2_decode_oer;
oer_type_encoder_f VehicleHeight2_encode_oer;
per_type_decoder_f VehicleHeight2_decode_uper;
per_type_encoder_f VehicleHeight2_encode_uper;
per_type_decoder_f VehicleHeight2_decode_aper;
per_type_encoder_f VehicleHeight2_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleHeight2_H_ */
#include "asn_internal.h"
