version: '2.4'
services:
    rsu:
        hostname: rsu
        image: vanetza:test
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS="6e:06:e0:03:00:01"
            - VANETZA_LATITUDE=40.5
            - VANETZA_LONGITUDE=-8.5
            - VANETZA_ALTITUDE=20
            - VANETZA_CAM=true
            - VANETZA_CAM_PERIODIC=true
            - VANETZA_DENM=true
            - VANETZA_CPM=true
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10

    obu:
        hostname: obu
        image: vanetza:test
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20
            
networks:
  vanetzalan0:
    external: true
    name: vanetzalan0