version: '2.4'
services:
    rsu:
        hostname: rsu
        image: vanetza:test
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10

    obu:
        hostname: obu
        image: vanetza:test
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20
            
networks:
  vanetzalan0:
    external: true
    name: vanetzalan0