/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "asn1/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#include "AcceptabilityStatus.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_AcceptabilityStatus_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_AcceptabilityStatus_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_AcceptabilityStatus_value2enum_1[] = {
	{ 1,	11,	"acceptation" },
	{ 2,	20,	"refuseRoadSafetyRisk" },
	{ 3,	29,	"refuseCooperationCostTooHight" },
	{ 4,	27,	"refuseMissbehaviourDetected" },
	{ 5,	30,	"refuseTrafficRulesNotRespected" },
	{ 6,	14,	"offeredRefused" }
};
static const unsigned int asn_MAP_AcceptabilityStatus_enum2value_1[] = {
	0,	/* acceptation(1) */
	5,	/* offeredRefused(6) */
	2,	/* refuseCooperationCostTooHight(3) */
	3,	/* refuseMissbehaviourDetected(4) */
	1,	/* refuseRoadSafetyRisk(2) */
	4	/* refuseTrafficRulesNotRespected(5) */
};
const asn_INTEGER_specifics_t asn_SPC_AcceptabilityStatus_specs_1 = {
	asn_MAP_AcceptabilityStatus_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_AcceptabilityStatus_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_AcceptabilityStatus_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_AcceptabilityStatus = {
	"AcceptabilityStatus",
	"AcceptabilityStatus",
	&asn_OP_NativeEnumerated,
	asn_DEF_AcceptabilityStatus_tags_1,
	sizeof(asn_DEF_AcceptabilityStatus_tags_1)
		/sizeof(asn_DEF_AcceptabilityStatus_tags_1[0]), /* 1 */
	asn_DEF_AcceptabilityStatus_tags_1,	/* Same as above */
	sizeof(asn_DEF_AcceptabilityStatus_tags_1)
		/sizeof(asn_DEF_AcceptabilityStatus_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_AcceptabilityStatus_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_AcceptabilityStatus_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_AcceptabilityStatus_specs_1	/* Additional specs */
};

