/*
 * Generated by asn1c
 * From ASN.1 module "DSRC"
 * 	found in "ISO19091.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -R`
 */

#include "BasicVehicleRole.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_BasicVehicleRole_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_BasicVehicleRole_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  5,  5,  0,  22 }	/* (0..22,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_BasicVehicleRole_value2enum_1[] = {
	{ 0,	12,	"basicVehicle" },
	{ 1,	15,	"publicTransport" },
	{ 2,	16,	"specialTransport" },
	{ 3,	14,	"dangerousGoods" },
	{ 4,	8,	"roadWork" },
	{ 5,	10,	"roadRescue" },
	{ 6,	9,	"emergency" },
	{ 7,	9,	"safetyCar" },
	{ 8,	12,	"none-unknown" },
	{ 9,	5,	"truck" },
	{ 10,	10,	"motorcycle" },
	{ 11,	14,	"roadSideSource" },
	{ 12,	6,	"police" },
	{ 13,	4,	"fire" },
	{ 14,	9,	"ambulance" },
	{ 15,	3,	"dot" },
	{ 16,	7,	"transit" },
	{ 17,	10,	"slowMoving" },
	{ 18,	7,	"stopNgo" },
	{ 19,	7,	"cyclist" },
	{ 20,	10,	"pedestrian" },
	{ 21,	12,	"nonMotorized" },
	{ 22,	8,	"military" }
	/* This list is extensible */
};
static int asn_validate_BasicVehicleRole(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_BasicVehicleRole value = *(e_BasicVehicleRole*)sptr;
    switch(value) {
    case BasicVehicleRole_basicVehicle:
    case BasicVehicleRole_publicTransport:
    case BasicVehicleRole_specialTransport:
    case BasicVehicleRole_dangerousGoods:
    case BasicVehicleRole_roadWork:
    case BasicVehicleRole_roadRescue:
    case BasicVehicleRole_emergency:
    case BasicVehicleRole_safetyCar:
    case BasicVehicleRole_none_unknown:
    case BasicVehicleRole_truck:
    case BasicVehicleRole_motorcycle:
    case BasicVehicleRole_roadSideSource:
    case BasicVehicleRole_police:
    case BasicVehicleRole_fire:
    case BasicVehicleRole_ambulance:
    case BasicVehicleRole_dot:
    case BasicVehicleRole_transit:
    case BasicVehicleRole_slowMoving:
    case BasicVehicleRole_stopNgo:
    case BasicVehicleRole_cyclist:
    case BasicVehicleRole_pedestrian:
    case BasicVehicleRole_nonMotorized:
    case BasicVehicleRole_military:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_BasicVehicleRole_enum2value_1[] = {
	14,	/* ambulance(14) */
	0,	/* basicVehicle(0) */
	19,	/* cyclist(19) */
	3,	/* dangerousGoods(3) */
	15,	/* dot(15) */
	6,	/* emergency(6) */
	13,	/* fire(13) */
	22,	/* military(22) */
	10,	/* motorcycle(10) */
	21,	/* nonMotorized(21) */
	8,	/* none-unknown(8) */
	20,	/* pedestrian(20) */
	12,	/* police(12) */
	1,	/* publicTransport(1) */
	5,	/* roadRescue(5) */
	11,	/* roadSideSource(11) */
	4,	/* roadWork(4) */
	7,	/* safetyCar(7) */
	17,	/* slowMoving(17) */
	2,	/* specialTransport(2) */
	18,	/* stopNgo(18) */
	16,	/* transit(16) */
	9	/* truck(9) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_BasicVehicleRole_specs_1 = {
	asn_MAP_BasicVehicleRole_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_BasicVehicleRole_enum2value_1,	/* N => "tag"; sorted by N */
	23,	/* Number of elements in the maps */
	24,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_BasicVehicleRole_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_BasicVehicleRole = {
	"BasicVehicleRole",
	"BasicVehicleRole",
	&asn_OP_NativeEnumerated,
	asn_DEF_BasicVehicleRole_tags_1,
	sizeof(asn_DEF_BasicVehicleRole_tags_1)
		/sizeof(asn_DEF_BasicVehicleRole_tags_1[0]), /* 1 */
	asn_DEF_BasicVehicleRole_tags_1,	/* Same as above */
	sizeof(asn_DEF_BasicVehicleRole_tags_1)
		/sizeof(asn_DEF_BasicVehicleRole_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_BasicVehicleRole_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_BasicVehicleRole_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_BasicVehicleRole
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_BasicVehicleRole_specs_1	/* Additional specs */
};

