/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "iso/CDD-Release2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_BrakeControl_H_
#define	_BrakeControl_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BrakeControl {
	BrakeControl_abs	= 0,
	BrakeControl_tcs	= 1,
	BrakeControl_esc	= 2
} e_BrakeControl;

/* BrakeControl */
typedef BIT_STRING_t	 BrakeControl_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_BrakeControl_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BrakeControl;
asn_struct_free_f BrakeControl_free;
asn_struct_print_f BrakeControl_print;
asn_constr_check_f BrakeControl_constraint;
ber_type_decoder_f BrakeControl_decode_ber;
der_type_encoder_f BrakeControl_encode_der;
xer_type_decoder_f BrakeControl_decode_xer;
xer_type_encoder_f BrakeControl_encode_xer;
jer_type_encoder_f BrakeControl_encode_jer;
oer_type_decoder_f BrakeControl_decode_oer;
oer_type_encoder_f BrakeControl_encode_oer;
per_type_decoder_f BrakeControl_decode_uper;
per_type_encoder_f BrakeControl_encode_uper;
per_type_decoder_f BrakeControl_decode_aper;
per_type_encoder_f BrakeControl_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _BrakeControl_H_ */
#include "asn_internal.h"
