/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "asn1/EN302637-2v141-CAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_CAM_PDU_Descriptions_SpecialVehicleContainer_H_
#define	_CAM_PDU_Descriptions_SpecialVehicleContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CAM-PDU-Descriptions_PublicTransportContainer.h"
#include "CAM-PDU-Descriptions_SpecialTransportContainer.h"
#include "CAM-PDU-Descriptions_DangerousGoodsContainer.h"
#include "CAM-PDU-Descriptions_RoadWorksContainerBasic.h"
#include "CAM-PDU-Descriptions_RescueContainer.h"
#include "CAM-PDU-Descriptions_EmergencyContainer.h"
#include "CAM-PDU-Descriptions_SafetyCarContainer.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CAM_PDU_Descriptions_SpecialVehicleContainer_PR {
	CAM_PDU_Descriptions_SpecialVehicleContainer_PR_NOTHING,	/* No components present */
	CAM_PDU_Descriptions_SpecialVehicleContainer_PR_publicTransportContainer,
	CAM_PDU_Descriptions_SpecialVehicleContainer_PR_specialTransportContainer,
	CAM_PDU_Descriptions_SpecialVehicleContainer_PR_dangerousGoodsContainer,
	CAM_PDU_Descriptions_SpecialVehicleContainer_PR_roadWorksContainerBasic,
	CAM_PDU_Descriptions_SpecialVehicleContainer_PR_rescueContainer,
	CAM_PDU_Descriptions_SpecialVehicleContainer_PR_emergencyContainer,
	CAM_PDU_Descriptions_SpecialVehicleContainer_PR_safetyCarContainer
	/* Extensions may appear below */
	
} CAM_PDU_Descriptions_SpecialVehicleContainer_PR;

/* CAM-PDU-Descriptions_SpecialVehicleContainer */
typedef struct CAM_PDU_Descriptions_SpecialVehicleContainer {
	CAM_PDU_Descriptions_SpecialVehicleContainer_PR present;
	union CAM_PDU_Descriptions_SpecialVehicleContainer_u {
		CAM_PDU_Descriptions_PublicTransportContainer_t	 publicTransportContainer;
		CAM_PDU_Descriptions_SpecialTransportContainer_t	 specialTransportContainer;
		CAM_PDU_Descriptions_DangerousGoodsContainer_t	 dangerousGoodsContainer;
		CAM_PDU_Descriptions_RoadWorksContainerBasic_t	 roadWorksContainerBasic;
		CAM_PDU_Descriptions_RescueContainer_t	 rescueContainer;
		CAM_PDU_Descriptions_EmergencyContainer_t	 emergencyContainer;
		CAM_PDU_Descriptions_SafetyCarContainer_t	 safetyCarContainer;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CAM_PDU_Descriptions_SpecialVehicleContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAM_PDU_Descriptions_SpecialVehicleContainer;
extern asn_CHOICE_specifics_t asn_SPC_CAM_PDU_Descriptions_SpecialVehicleContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_CAM_PDU_Descriptions_SpecialVehicleContainer_1[7];
extern asn_per_constraints_t asn_PER_type_CAM_PDU_Descriptions_SpecialVehicleContainer_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CAM_PDU_Descriptions_SpecialVehicleContainer_H_ */
#include "asn_internal.h"
