/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Description"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_CAM_PDU_Description_CamParameters_H_
#define	_CAM_PDU_Description_CamParameters_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_BasicContainer.h"
#include "CAM-PDU-Description_HighFrequencyContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CAM_PDU_Description_LowFrequencyContainer;
struct CAM_PDU_Description_SpecialVehicleContainer;
struct WrappedExtensionContainers;

/* CAM-PDU-Description_CamParameters */
typedef struct CAM_PDU_Description_CamParameters {
	ETSI_ITS_CDD_BasicContainer_t	 basicContainer;
	CAM_PDU_Description_HighFrequencyContainer_t	 highFrequencyContainer;
	struct CAM_PDU_Description_LowFrequencyContainer	*lowFrequencyContainer;	/* OPTIONAL */
	struct CAM_PDU_Description_SpecialVehicleContainer	*specialVehicleContainer;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct WrappedExtensionContainers	*extensionContainers;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CAM_PDU_Description_CamParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAM_PDU_Description_CamParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_CAM_PDU_Description_CamParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_CAM_PDU_Description_CamParameters_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CAM-PDU-Description_LowFrequencyContainer.h"
#include "CAM-PDU-Description_SpecialVehicleContainer.h"
#include "WrappedExtensionContainers.h"

#endif	/* _CAM_PDU_Description_CamParameters_H_ */
#include "asn_internal.h"
