/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Description"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_CAM_PDU_Description_SafetyCarContainer_H_
#define	_CAM_PDU_Description_SafetyCarContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_LightBarSirenInUse.h"
#include "ETSI-ITS-CDD_TrafficRule.h"
#include "ETSI-ITS-CDD_SpeedLimit.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CauseCodeV2;

/* CAM-PDU-Description_SafetyCarContainer */
typedef struct CAM_PDU_Description_SafetyCarContainer {
	ETSI_ITS_CDD_LightBarSirenInUse_t	 lightBarSirenInUse;
	struct CauseCodeV2	*incidentIndication;	/* OPTIONAL */
	ETSI_ITS_CDD_TrafficRule_t	*trafficRule;	/* OPTIONAL */
	ETSI_ITS_CDD_SpeedLimit_t	*speedLimit;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CAM_PDU_Description_SafetyCarContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAM_PDU_Description_SafetyCarContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_CAM_PDU_Description_SafetyCarContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_CAM_PDU_Description_SafetyCarContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CauseCodeV2.h"

#endif	/* _CAM_PDU_Description_SafetyCarContainer_H_ */
#include "asn_internal.h"
