/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EV-RechargingSpotReservation-PDU-Descriptions"
 * 	found in "/home/rrosmaninho/vanetza/asn1/EV-RSR-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R -D /home/rrosmaninho/vanetza/vanetza/asn1/its`
 */

#ifndef	_CancellationRequestMessage_H_
#define	_CancellationRequestMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Reservation-ID.h"
#include "Reservation-Password.h"
#include "TimestampUTC.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CancellationRequestMessage */
typedef struct CancellationRequestMessage {
	Reservation_ID_t	 reservation_ID;
	Reservation_Password_t	 reservation_Password;
	TimestampUTC_t	 currentTime;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CancellationRequestMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CancellationRequestMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_CancellationRequestMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_CancellationRequestMessage_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CancellationRequestMessage_H_ */
#include "asn_internal.h"
