/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Description"
 * 	found in "asn1/DENM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_DENM_PDU_Description_StationaryVehicleContainer_H_
#define	_DENM_PDU_Description_StationaryVehicleContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_StationarySince.h"
#include "ETSI-ITS-CDD_NumberOfOccupants.h"
#include "ETSI-ITS-CDD_EnergyStorageType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CauseCodeV2;
struct ETSI_ITS_CDD_DangerousGoodsExtended;
struct ETSI_ITS_CDD_VehicleIdentification;

/* DENM-PDU-Description_StationaryVehicleContainer */
typedef struct DENM_PDU_Description_StationaryVehicleContainer {
	ETSI_ITS_CDD_StationarySince_t	*stationarySince;	/* OPTIONAL */
	struct CauseCodeV2	*stationaryCause;	/* OPTIONAL */
	struct ETSI_ITS_CDD_DangerousGoodsExtended	*carryingDangerousGoods;	/* OPTIONAL */
	ETSI_ITS_CDD_NumberOfOccupants_t	*numberOfOccupants;	/* OPTIONAL */
	struct ETSI_ITS_CDD_VehicleIdentification	*vehicleIdentification;	/* OPTIONAL */
	ETSI_ITS_CDD_EnergyStorageType_t	*energyStorageType;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DENM_PDU_Description_StationaryVehicleContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DENM_PDU_Description_StationaryVehicleContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_DENM_PDU_Description_StationaryVehicleContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_DENM_PDU_Description_StationaryVehicleContainer_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CauseCodeV2.h"
#include "ETSI-ITS-CDD_DangerousGoodsExtended.h"
#include "ETSI-ITS-CDD_VehicleIdentification.h"

#endif	/* _DENM_PDU_Description_StationaryVehicleContainer_H_ */
#include "asn_internal.h"
