/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Description"
 * 	found in "asn1/DENM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_DenmPayload_H_
#define	_DenmPayload_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DENM-PDU-Description_ManagementContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DENM_PDU_Description_SituationContainer;
struct DENM_PDU_Description_LocationContainer;
struct DENM_PDU_Description_AlacarteContainer;

/* DenmPayload */
typedef struct DenmPayload {
	DENM_PDU_Description_ManagementContainer_t	 management;
	struct DENM_PDU_Description_SituationContainer	*situation;	/* OPTIONAL */
	struct DENM_PDU_Description_LocationContainer	*location;	/* OPTIONAL */
	struct DENM_PDU_Description_AlacarteContainer	*alacarte;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DenmPayload_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DenmPayload;
extern asn_SEQUENCE_specifics_t asn_SPC_DenmPayload_specs_1;
extern asn_TYPE_member_t asn_MBR_DenmPayload_1[4];
extern asn_per_constraints_t asn_PER_type_DenmPayload_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DENM-PDU-Description_SituationContainer.h"
#include "DENM-PDU-Description_LocationContainer.h"
#include "DENM-PDU-Description_AlacarteContainer.h"

#endif	/* _DenmPayload_H_ */
#include "asn_internal.h"
