/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Description"
 * 	found in "asn1/DENM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_DENM_PDU_Description_RoadConfigurationContainer_H_
#define	_DENM_PDU_Description_RoadConfigurationContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MetaInformation.h"
#include "RoadConfigurationSectionList.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DENM-PDU-Description_RoadConfigurationContainer */
typedef struct DENM_PDU_Description_RoadConfigurationContainer {
	MetaInformation_t	 roadConfigurationConfidence;
	RoadConfigurationSectionList_t	 roadConfigurationSectionList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DENM_PDU_Description_RoadConfigurationContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DENM_PDU_Description_RoadConfigurationContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_DENM_PDU_Description_RoadConfigurationContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_DENM_PDU_Description_RoadConfigurationContainer_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DENM_PDU_Description_RoadConfigurationContainer_H_ */
#include "asn_internal.h"
