/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EV-RechargingSpotReservation-PDU-Descriptions"
 * 	found in "/home/rrosmaninho/vanetza/asn1/EV-RSR-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R -D /home/rrosmaninho/vanetza/vanetza/asn1/its`
 */

#ifndef	_EAmount_H_
#define	_EAmount_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EAmount {
	EAmount_oneWh	= 1
} e_EAmount;

/* EAmount */
typedef long	 EAmount_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EAmount_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EAmount;
asn_struct_free_f EAmount_free;
asn_struct_print_f EAmount_print;
asn_constr_check_f EAmount_constraint;
ber_type_decoder_f EAmount_decode_ber;
der_type_encoder_f EAmount_encode_der;
xer_type_decoder_f EAmount_decode_xer;
xer_type_encoder_f EAmount_encode_xer;
oer_type_decoder_f EAmount_decode_oer;
oer_type_encoder_f EAmount_encode_oer;
per_type_decoder_f EAmount_decode_uper;
per_type_encoder_f EAmount_encode_uper;
per_type_decoder_f EAmount_decode_aper;
per_type_encoder_f EAmount_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EAmount_H_ */
#include "asn_internal.h"
