/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "iso/CDD-Release2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_VruSubProfileBicyclist_H_
#define	_ETSI_ITS_CDD_VruSubProfileBicyclist_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ETSI_ITS_CDD_VruSubProfileBicyclist {
	ETSI_ITS_CDD_VruSubProfileBicyclist_unavailable	= 0,
	ETSI_ITS_CDD_VruSubProfileBicyclist_bicyclist	= 1,
	ETSI_ITS_CDD_VruSubProfileBicyclist_wheelchair_user	= 2,
	ETSI_ITS_CDD_VruSubProfileBicyclist_horse_and_rider	= 3,
	ETSI_ITS_CDD_VruSubProfileBicyclist_rollerskater	= 4,
	ETSI_ITS_CDD_VruSubProfileBicyclist_e_scooter	= 5,
	ETSI_ITS_CDD_VruSubProfileBicyclist_personal_transporter	= 6,
	ETSI_ITS_CDD_VruSubProfileBicyclist_pedelec	= 7,
	ETSI_ITS_CDD_VruSubProfileBicyclist_speed_pedelec	= 8,
	ETSI_ITS_CDD_VruSubProfileBicyclist_roadbike	= 9,
	ETSI_ITS_CDD_VruSubProfileBicyclist_childrensbike	= 10
} e_ETSI_ITS_CDD_VruSubProfileBicyclist;

/* ETSI-ITS-CDD_VruSubProfileBicyclist */
typedef long	 ETSI_ITS_CDD_VruSubProfileBicyclist_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ETSI_ITS_CDD_VruSubProfileBicyclist_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_VruSubProfileBicyclist;
asn_struct_free_f ETSI_ITS_CDD_VruSubProfileBicyclist_free;
asn_struct_print_f ETSI_ITS_CDD_VruSubProfileBicyclist_print;
asn_constr_check_f ETSI_ITS_CDD_VruSubProfileBicyclist_constraint;
ber_type_decoder_f ETSI_ITS_CDD_VruSubProfileBicyclist_decode_ber;
der_type_encoder_f ETSI_ITS_CDD_VruSubProfileBicyclist_encode_der;
xer_type_decoder_f ETSI_ITS_CDD_VruSubProfileBicyclist_decode_xer;
xer_type_encoder_f ETSI_ITS_CDD_VruSubProfileBicyclist_encode_xer;
jer_type_encoder_f ETSI_ITS_CDD_VruSubProfileBicyclist_encode_jer;
oer_type_decoder_f ETSI_ITS_CDD_VruSubProfileBicyclist_decode_oer;
oer_type_encoder_f ETSI_ITS_CDD_VruSubProfileBicyclist_encode_oer;
per_type_decoder_f ETSI_ITS_CDD_VruSubProfileBicyclist_decode_uper;
per_type_encoder_f ETSI_ITS_CDD_VruSubProfileBicyclist_encode_uper;
per_type_decoder_f ETSI_ITS_CDD_VruSubProfileBicyclist_decode_aper;
per_type_encoder_f ETSI_ITS_CDD_VruSubProfileBicyclist_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_VruSubProfileBicyclist_H_ */
#include "asn_internal.h"
