/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "iso/CDD-Release2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_AccelerationChangeIndication_H_
#define	_ETSI_ITS_CDD_AccelerationChangeIndication_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AccelerationChange.h"
#include "DeltaTimeTenthOfSecond.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ETSI-ITS-CDD_AccelerationChangeIndication */
typedef struct ETSI_ITS_CDD_AccelerationChangeIndication {
	AccelerationChange_t	 accelOrDecel;
	DeltaTimeTenthOfSecond_t	 actionDeltaTime;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ETSI_ITS_CDD_AccelerationChangeIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_AccelerationChangeIndication;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_AccelerationChangeIndication_H_ */
#include "asn_internal.h"
