/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "iso/CDD-Release2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_VruSpecificExteriorLights_H_
#define	_ETSI_ITS_CDD_VruSpecificExteriorLights_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ETSI_ITS_CDD_VruSpecificExteriorLights {
	ETSI_ITS_CDD_VruSpecificExteriorLights_unavailable	= 0,
	ETSI_ITS_CDD_VruSpecificExteriorLights_backFlashLight	= 1,
	ETSI_ITS_CDD_VruSpecificExteriorLights_helmetLight	= 2,
	ETSI_ITS_CDD_VruSpecificExteriorLights_armLight	= 3,
	ETSI_ITS_CDD_VruSpecificExteriorLights_legLight	= 4,
	ETSI_ITS_CDD_VruSpecificExteriorLights_wheelLight	= 5
} e_ETSI_ITS_CDD_VruSpecificExteriorLights;

/* ETSI-ITS-CDD_VruSpecificExteriorLights */
typedef BIT_STRING_t	 ETSI_ITS_CDD_VruSpecificExteriorLights_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ETSI_ITS_CDD_VruSpecificExteriorLights_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_VruSpecificExteriorLights;
asn_struct_free_f ETSI_ITS_CDD_VruSpecificExteriorLights_free;
asn_struct_print_f ETSI_ITS_CDD_VruSpecificExteriorLights_print;
asn_constr_check_f ETSI_ITS_CDD_VruSpecificExteriorLights_constraint;
ber_type_decoder_f ETSI_ITS_CDD_VruSpecificExteriorLights_decode_ber;
der_type_encoder_f ETSI_ITS_CDD_VruSpecificExteriorLights_encode_der;
xer_type_decoder_f ETSI_ITS_CDD_VruSpecificExteriorLights_decode_xer;
xer_type_encoder_f ETSI_ITS_CDD_VruSpecificExteriorLights_encode_xer;
jer_type_encoder_f ETSI_ITS_CDD_VruSpecificExteriorLights_encode_jer;
oer_type_decoder_f ETSI_ITS_CDD_VruSpecificExteriorLights_decode_oer;
oer_type_encoder_f ETSI_ITS_CDD_VruSpecificExteriorLights_encode_oer;
per_type_decoder_f ETSI_ITS_CDD_VruSpecificExteriorLights_decode_uper;
per_type_encoder_f ETSI_ITS_CDD_VruSpecificExteriorLights_encode_uper;
per_type_decoder_f ETSI_ITS_CDD_VruSpecificExteriorLights_decode_aper;
per_type_encoder_f ETSI_ITS_CDD_VruSpecificExteriorLights_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_VruSpecificExteriorLights_H_ */
#include "asn_internal.h"
