/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IMZM-PDU-Descriptions"
 * 	found in "asn1/IMZM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_InterferenceManagementZoneMessage_H_
#define	_InterferenceManagementZoneMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GenerationDeltaTime.h"
#include "ImzmParameters.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* InterferenceManagementZoneMessage */
typedef struct InterferenceManagementZoneMessage {
	GenerationDeltaTime_t	 generationDeltaTime;
	ImzmParameters_t	 imzmParameters;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterferenceManagementZoneMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterferenceManagementZoneMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_InterferenceManagementZoneMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_InterferenceManagementZoneMessage_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _InterferenceManagementZoneMessage_H_ */
#include "asn_internal.h"
