/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "asn1/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ItsId_H_
#define	_ItsId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ItsId */
typedef long	 ItsId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ItsId;
asn_struct_free_f ItsId_free;
asn_struct_print_f ItsId_print;
asn_constr_check_f ItsId_constraint;
ber_type_decoder_f ItsId_decode_ber;
der_type_encoder_f ItsId_encode_der;
xer_type_decoder_f ItsId_decode_xer;
xer_type_encoder_f ItsId_encode_xer;
jer_type_encoder_f ItsId_encode_jer;
oer_type_decoder_f ItsId_decode_oer;
oer_type_encoder_f ItsId_encode_oer;
per_type_decoder_f ItsId_decode_uper;
per_type_encoder_f ItsId_encode_uper;
per_type_decoder_f ItsId_decode_aper;
per_type_encoder_f ItsId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ItsId_H_ */
#include "asn_internal.h"
