/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "iso/ISO19321.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_IVI_PolygonalLine_H_
#define	_IVI_PolygonalLine_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IVI_DeltaPositions.h"
#include "IVI_DeltaReferencePositions.h"
#include "AbsolutePositions.h"
#include "AbsolutePositionsWAltitude.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IVI_PolygonalLine_PR {
	IVI_PolygonalLine_PR_NOTHING,	/* No components present */
	IVI_PolygonalLine_PR_deltaPositions,
	IVI_PolygonalLine_PR_deltaPositionsWithAltitude,
	IVI_PolygonalLine_PR_absolutePositions,
	IVI_PolygonalLine_PR_absolutePositionsWithAltitude
	/* Extensions may appear below */
	
} IVI_PolygonalLine_PR;

/* IVI_PolygonalLine */
typedef struct IVI_PolygonalLine {
	IVI_PolygonalLine_PR present;
	union IVI_PolygonalLine_u {
		IVI_DeltaPositions_t	 deltaPositions;
		IVI_DeltaReferencePositions_t	 deltaPositionsWithAltitude;
		AbsolutePositions_t	 absolutePositions;
		AbsolutePositionsWAltitude_t	 absolutePositionsWithAltitude;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IVI_PolygonalLine_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IVI_PolygonalLine;
extern asn_CHOICE_specifics_t asn_SPC_IVI_PolygonalLine_specs_1;
extern asn_TYPE_member_t asn_MBR_IVI_PolygonalLine_1[4];
extern asn_per_constraints_t asn_PER_type_IVI_PolygonalLine_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _IVI_PolygonalLine_H_ */
#include "asn_internal.h"
