/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "iso/ISO19321.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_IviManagementContainer_H_
#define	_IviManagementContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EfcDsrcApplication_Provider.h"
#include "IVI_IviIdentificationNumber.h"
#include "ITS-Container_TimestampIts.h"
#include "IviStatus.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IviIdentificationNumbers;
struct ConnectedDenms;

/* IviManagementContainer */
typedef struct IviManagementContainer {
	EfcDsrcApplication_Provider_t	 serviceProviderId;
	IVI_IviIdentificationNumber_t	 iviIdentificationNumber;
	ITS_Container_TimestampIts_t	*timeStamp;	/* OPTIONAL */
	ITS_Container_TimestampIts_t	*validFrom;	/* OPTIONAL */
	ITS_Container_TimestampIts_t	*validTo;	/* OPTIONAL */
	struct IviIdentificationNumbers	*connectedIviStructures;	/* OPTIONAL */
	IviStatus_t	 iviStatus;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct ConnectedDenms	*connectedDenms;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IviManagementContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IviManagementContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_IviManagementContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_IviManagementContainer_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IviIdentificationNumbers.h"
#include "ConnectedDenms.h"

#endif	/* _IviManagementContainer_H_ */
#include "asn_internal.h"
