/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "asn1/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_Maneuvers_H_
#define	_Maneuvers_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Maneuver;

/* Maneuvers */
typedef struct Maneuvers {
	A_SEQUENCE_OF(struct Maneuver) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Maneuvers_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Maneuvers;
extern asn_SET_OF_specifics_t asn_SPC_Maneuvers_specs_1;
extern asn_TYPE_member_t asn_MBR_Maneuvers_1[1];
extern asn_per_constraints_t asn_PER_type_Maneuvers_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Maneuver.h"

#endif	/* _Maneuvers_H_ */
#include "asn_internal.h"
