/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "asn1/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ManoeuvreAdviceContainer_H_
#define	_ManoeuvreAdviceContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExecutantData;

/* ManoeuvreAdviceContainer */
typedef struct ManoeuvreAdviceContainer {
	long	 numberOfExecutant;
	struct ManoeuvreAdviceContainer__executantData {
		A_SEQUENCE_OF(struct ExecutantData) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} executantData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManoeuvreAdviceContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManoeuvreAdviceContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_ManoeuvreAdviceContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ManoeuvreAdviceContainer_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExecutantData.h"

#endif	/* _ManoeuvreAdviceContainer_H_ */
#include "asn_internal.h"
