/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "asn1/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ManoeuvresCoordinationConcept_H_
#define	_ManoeuvresCoordinationConcept_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ManoeuvresCoordinationConcept {
	ManoeuvresCoordinationConcept_agreementSeekingRequest	= 0,
	ManoeuvresCoordinationConcept_agreementSeekingOffer	= 1,
	ManoeuvresCoordinationConcept_prescriptiveInterception	= 2,
	ManoeuvresCoordinationConcept_prescriptiveRoadSafety	= 3,
	ManoeuvresCoordinationConcept_prescriptiveGlobalTrafficManagement	= 4,
	ManoeuvresCoordinationConcept_prescriptiveLocalTrafficManagement	= 5
} e_ManoeuvresCoordinationConcept;

/* ManoeuvresCoordinationConcept */
typedef long	 ManoeuvresCoordinationConcept_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ManoeuvresCoordinationConcept_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ManoeuvresCoordinationConcept;
extern const asn_INTEGER_specifics_t asn_SPC_ManoeuvresCoordinationConcept_specs_1;
asn_struct_free_f ManoeuvresCoordinationConcept_free;
asn_struct_print_f ManoeuvresCoordinationConcept_print;
asn_constr_check_f ManoeuvresCoordinationConcept_constraint;
ber_type_decoder_f ManoeuvresCoordinationConcept_decode_ber;
der_type_encoder_f ManoeuvresCoordinationConcept_encode_der;
xer_type_decoder_f ManoeuvresCoordinationConcept_decode_xer;
xer_type_encoder_f ManoeuvresCoordinationConcept_encode_xer;
oer_type_decoder_f ManoeuvresCoordinationConcept_decode_oer;
oer_type_encoder_f ManoeuvresCoordinationConcept_encode_oer;
per_type_decoder_f ManoeuvresCoordinationConcept_decode_uper;
per_type_encoder_f ManoeuvresCoordinationConcept_encode_uper;
per_type_decoder_f ManoeuvresCoordinationConcept_decode_aper;
per_type_encoder_f ManoeuvresCoordinationConcept_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ManoeuvresCoordinationConcept_H_ */
#include "asn_internal.h"
