/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "asn1/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_MCMParameter_H_
#define	_MCMParameter_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BasicContainerMCM.h"
#include "ManoeuvresCoordinationContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AgreementSeekingContainer;
struct PrescriptiveContainer;
struct ResponseContainer;

/* MCMParameter */
typedef struct MCMParameter {
	BasicContainerMCM_t	 basicContainer;
	ManoeuvresCoordinationContainer_t	 manoeuvresCoordinationContainer;
	struct AgreementSeekingContainer	*agreementSeekingContainer;	/* OPTIONAL */
	struct PrescriptiveContainer	*prescriptiveContainer;	/* OPTIONAL */
	struct ResponseContainer	*responseContainer;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MCMParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MCMParameter;
extern asn_SEQUENCE_specifics_t asn_SPC_MCMParameter_specs_1;
extern asn_TYPE_member_t asn_MBR_MCMParameter_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AgreementSeekingContainer.h"
#include "PrescriptiveContainer.h"
#include "ResponseContainer.h"

#endif	/* _MCMParameter_H_ */
#include "asn_internal.h"
