/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "iso/CDD-Release2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_PedalPositionValue_H_
#define	_PedalPositionValue_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PedalPositionValue {
	PedalPositionValue_notPressed	= 0,
	PedalPositionValue_fullyPressed	= 10,
	PedalPositionValue_unavailable	= 11
} e_PedalPositionValue;

/* PedalPositionValue */
typedef long	 PedalPositionValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PedalPositionValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PedalPositionValue;
asn_struct_free_f PedalPositionValue_free;
asn_struct_print_f PedalPositionValue_print;
asn_constr_check_f PedalPositionValue_constraint;
ber_type_decoder_f PedalPositionValue_decode_ber;
der_type_encoder_f PedalPositionValue_encode_der;
xer_type_decoder_f PedalPositionValue_decode_xer;
xer_type_encoder_f PedalPositionValue_encode_xer;
jer_type_encoder_f PedalPositionValue_encode_jer;
oer_type_decoder_f PedalPositionValue_decode_oer;
oer_type_encoder_f PedalPositionValue_encode_oer;
per_type_decoder_f PedalPositionValue_decode_uper;
per_type_encoder_f PedalPositionValue_encode_uper;
per_type_decoder_f PedalPositionValue_decode_aper;
per_type_encoder_f PedalPositionValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PedalPositionValue_H_ */
#include "asn_internal.h"
