/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "asn1/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ResponseContainer_H_
#define	_ResponseContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MCMCategory.h"
#include "AcceptabilityStatus.h"
#include "Trajectory.h"
#include "VehicleAutomationLevel.h"
#include "CooperationCost.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ResponseContainer */
typedef struct ResponseContainer {
	MCMCategory_t	 mcmCategory;
	AcceptabilityStatus_t	 acceptabilityStatus;
	Trajectory_t	 vehicleReferenceTrajectory;
	VehicleAutomationLevel_t	 vehicleAutomationLevel;
	CooperationCost_t	 estimatedCooperationCost;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResponseContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResponseContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_ResponseContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ResponseContainer_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _ResponseContainer_H_ */
#include "asn_internal.h"
