/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TIS-TPG-Transactions-Descriptions"
 * 	found in "asn1/TIS-TPG-Transactions-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_TisTpgTRM_H_
#define	_TisTpgTRM_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TisTpgTRM-Management.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TisTpgTRM_Situation;
struct TisTpgTRM_Location;

/* TisTpgTRM */
typedef struct TisTpgTRM {
	TisTpgTRM_Management_t	 management;
	struct TisTpgTRM_Situation	*situation;	/* OPTIONAL */
	struct TisTpgTRM_Location	*location;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TisTpgTRM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TisTpgTRM;
extern asn_SEQUENCE_specifics_t asn_SPC_TisTpgTRM_specs_1;
extern asn_TYPE_member_t asn_MBR_TisTpgTRM_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TisTpgTRM-Situation.h"
#include "TisTpgTRM-Location.h"

#endif	/* _TisTpgTRM_H_ */
#include "asn_internal.h"
