/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TIS-TPG-Transactions-Descriptions"
 * 	found in "asn1/TIS-TPG-Transactions-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_TisTpgTransaction_H_
#define	_TisTpgTransaction_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TisTpgDRM.h"
#include "TisTpgSNM.h"
#include "TisTpgTRM.h"
#include "TisTpgTCM.h"
#include "TisTpgVDRM.h"
#include "TisTpgVDPM.h"
#include "TisTpgEOFM.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TisTpgTransaction_PR {
	TisTpgTransaction_PR_NOTHING,	/* No components present */
	TisTpgTransaction_PR_drm,
	TisTpgTransaction_PR_snm,
	TisTpgTransaction_PR_trm,
	TisTpgTransaction_PR_tcm,
	TisTpgTransaction_PR_vdrm,
	TisTpgTransaction_PR_vdpm,
	TisTpgTransaction_PR_eofm
} TisTpgTransaction_PR;

/* TisTpgTransaction */
typedef struct TisTpgTransaction {
	TisTpgTransaction_PR present;
	union TisTpgTransaction_u {
		TisTpgDRM_t	 drm;
		TisTpgSNM_t	 snm;
		TisTpgTRM_t	 trm;
		TisTpgTCM_t	 tcm;
		TisTpgVDRM_t	 vdrm;
		TisTpgVDPM_t	 vdpm;
		TisTpgEOFM_t	 eofm;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TisTpgTransaction_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TisTpgTransaction;
extern asn_CHOICE_specifics_t asn_SPC_TisTpgTransaction_specs_1;
extern asn_TYPE_member_t asn_MBR_TisTpgTransaction_1[7];
extern asn_per_constraints_t asn_PER_type_TisTpgTransaction_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TisTpgTransaction_H_ */
#include "asn_internal.h"
