/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TIS-TPG-Transactions-Descriptions"
 * 	found in "asn1/TIS-TPG-Transactions-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_TisTpgDRM_Situation_H_
#define	_TisTpgDRM_Situation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CauseCode.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TisTpgDRM-Situation */
typedef struct TisTpgDRM_Situation {
	CauseCode_t	 causeCode;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TisTpgDRM_Situation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TisTpgDRM_Situation;
extern asn_SEQUENCE_specifics_t asn_SPC_TisTpgDRM_Situation_specs_1;
extern asn_TYPE_member_t asn_MBR_TisTpgDRM_Situation_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _TisTpgDRM_Situation_H_ */
#include "asn_internal.h"
