/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TIS-TPG-Transactions-Descriptions"
 * 	found in "asn1/TIS-TPG-Transactions-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_TisTpgEOFM_Management_H_
#define	_TisTpgEOFM_Management_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TimestampIts.h"
#include "FillingStatus.h"
#include "NumberOfAppliedPressure.h"
#include "PairingID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AppliedTyrePressures;

/* TisTpgEOFM-Management */
typedef struct TisTpgEOFM_Management {
	TimestampIts_t	 generationTime;
	FillingStatus_t	 fillingStatus;
	NumberOfAppliedPressure_t	 numberOfAppliedPressure;
	struct AppliedTyrePressures	*appliedTyrePressures;	/* OPTIONAL */
	PairingID_t	*pairingID;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TisTpgEOFM_Management_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TisTpgEOFM_Management;
extern asn_SEQUENCE_specifics_t asn_SPC_TisTpgEOFM_Management_specs_1;
extern asn_TYPE_member_t asn_MBR_TisTpgEOFM_Management_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AppliedTyrePressures.h"

#endif	/* _TisTpgEOFM_Management_H_ */
#include "asn_internal.h"
