/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TIS-TPG-Transactions-Descriptions"
 * 	found in "asn1/TIS-TPG-Transactions-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_TisTpgTCM_H_
#define	_TisTpgTCM_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TisTpgTCM-Management.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TisTpgTCM_Situation;
struct TisTpgTCM_Location;

/* TisTpgTCM */
typedef struct TisTpgTCM {
	TisTpgTCM_Management_t	 management;
	struct TisTpgTCM_Situation	*situation;	/* OPTIONAL */
	struct TisTpgTCM_Location	*location;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TisTpgTCM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TisTpgTCM;
extern asn_SEQUENCE_specifics_t asn_SPC_TisTpgTCM_specs_1;
extern asn_TYPE_member_t asn_MBR_TisTpgTCM_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TisTpgTCM-Situation.h"
#include "TisTpgTCM-Location.h"

#endif	/* _TisTpgTCM_H_ */
#include "asn_internal.h"
