/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TIS-TPG-Transactions-Descriptions"
 * 	found in "asn1/TIS-TPG-Transactions-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_TisTpgSNM_Management_H_
#define	_TisTpgSNM_Management_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TimestampIts.h"
#include "TotalTpgStations.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TisTpgSNM-Management */
typedef struct TisTpgSNM_Management {
	TimestampIts_t	 generationTime;
	TotalTpgStations_t	 totalTpgStations;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TisTpgSNM_Management_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TisTpgSNM_Management;
extern asn_SEQUENCE_specifics_t asn_SPC_TisTpgSNM_Management_specs_1;
extern asn_TYPE_member_t asn_MBR_TisTpgSNM_Management_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TisTpgSNM_Management_H_ */
#include "asn_internal.h"
