/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TIS-TPG-Transactions-Descriptions"
 * 	found in "asn1/TIS-TPG-Transactions-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_TyreSetVariant_H_
#define	_TyreSetVariant_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TyreSetVariantID.h"
#include "TyreSidewallInformation.h"
#include "PressureVariantsList.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TyreSetVariant */
typedef struct TyreSetVariant {
	TyreSetVariantID_t	 variantID;
	TyreSidewallInformation_t	*frontAxleDimension;	/* OPTIONAL */
	TyreSidewallInformation_t	*rearAxleDimension;	/* OPTIONAL */
	PressureVariantsList_t	 pressureVariantsList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TyreSetVariant_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TyreSetVariant;
extern asn_SEQUENCE_specifics_t asn_SPC_TyreSetVariant_specs_1;
extern asn_TYPE_member_t asn_MBR_TyreSetVariant_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _TyreSetVariant_H_ */
#include "asn_internal.h"
