/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TIS-TPG-Transactions-Descriptions"
 * 	found in "asn1/TIS-TPG-Transactions-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_TyreData_H_
#define	_TyreData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TyrePressure.h"
#include "NULL.h"
#include "constr_CHOICE.h"
#include "TyreSidewallInformation.h"
#include "TyreAirTemperature.h"
#include "AxlePlacardPressure.h"
#include "TIN.h"
#include "SensorState.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TyreData__currentTyrePressure_PR {
	TyreData__currentTyrePressure_PR_NOTHING,	/* No components present */
	TyreData__currentTyrePressure_PR_tyrePressureValue,
	TyreData__currentTyrePressure_PR_unavailable
} TyreData__currentTyrePressure_PR;
typedef enum TyreData__tyreSidewallInformation_PR {
	TyreData__tyreSidewallInformation_PR_NOTHING,	/* No components present */
	TyreData__tyreSidewallInformation_PR_tyreSidewallInformationValue,
	TyreData__tyreSidewallInformation_PR_unavailable
} TyreData__tyreSidewallInformation_PR;
typedef enum TyreData__currentInsideAirTemperature_PR {
	TyreData__currentInsideAirTemperature_PR_NOTHING,	/* No components present */
	TyreData__currentInsideAirTemperature_PR_tyreAirTemperatureValue,
	TyreData__currentInsideAirTemperature_PR_unavailable
} TyreData__currentInsideAirTemperature_PR;
typedef enum TyreData__recommendedTyrePressure_PR {
	TyreData__recommendedTyrePressure_PR_NOTHING,	/* No components present */
	TyreData__recommendedTyrePressure_PR_axlePlacardPressureValue,
	TyreData__recommendedTyrePressure_PR_unavailable
} TyreData__recommendedTyrePressure_PR;
typedef enum TyreData__tin_PR {
	TyreData__tin_PR_NOTHING,	/* No components present */
	TyreData__tin_PR_tinValue,
	TyreData__tin_PR_unavailable
} TyreData__tin_PR;
typedef enum TyreData__sensorState_PR {
	TyreData__sensorState_PR_NOTHING,	/* No components present */
	TyreData__sensorState_PR_sensorStateValue,
	TyreData__sensorState_PR_unavailable
} TyreData__sensorState_PR;

/* TyreData */
typedef struct TyreData {
	struct TyreData__currentTyrePressure {
		TyreData__currentTyrePressure_PR present;
		union TyreData__currentTyrePressure_u {
			TyrePressure_t	 tyrePressureValue;
			NULL_t	 unavailable;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *currentTyrePressure;
	struct TyreData__tyreSidewallInformation {
		TyreData__tyreSidewallInformation_PR present;
		union TyreData__tyreSidewallInformation_u {
			TyreSidewallInformation_t	 tyreSidewallInformationValue;
			NULL_t	 unavailable;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tyreSidewallInformation;
	struct TyreData__currentInsideAirTemperature {
		TyreData__currentInsideAirTemperature_PR present;
		union TyreData__currentInsideAirTemperature_u {
			TyreAirTemperature_t	 tyreAirTemperatureValue;
			NULL_t	 unavailable;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *currentInsideAirTemperature;
	struct TyreData__recommendedTyrePressure {
		TyreData__recommendedTyrePressure_PR present;
		union TyreData__recommendedTyrePressure_u {
			AxlePlacardPressure_t	 axlePlacardPressureValue;
			NULL_t	 unavailable;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *recommendedTyrePressure;
	struct TyreData__tin {
		TyreData__tin_PR present;
		union TyreData__tin_u {
			TIN_t	 tinValue;
			NULL_t	 unavailable;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tin;
	struct TyreData__sensorState {
		TyreData__sensorState_PR present;
		union TyreData__sensorState_u {
			SensorState_t	 sensorStateValue;
			NULL_t	 unavailable;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sensorState;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TyreData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TyreData;
extern asn_SEQUENCE_specifics_t asn_SPC_TyreData_specs_1;
extern asn_TYPE_member_t asn_MBR_TyreData_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _TyreData_H_ */
#include "asn_internal.h"
