/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VAM_PDU_Descriptions_VruEnvironment_H_
#define	_VAM_PDU_Descriptions_VruEnvironment_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VAM_PDU_Descriptions_VruEnvironment {
	VAM_PDU_Descriptions_VruEnvironment_unavailable	= 0,
	VAM_PDU_Descriptions_VruEnvironment_intersectionCrossing	= 1,
	VAM_PDU_Descriptions_VruEnvironment_zebraCrossing	= 2,
	VAM_PDU_Descriptions_VruEnvironment_sidewalk	= 3,
	VAM_PDU_Descriptions_VruEnvironment_onVehicleRoad	= 4,
	VAM_PDU_Descriptions_VruEnvironment_protectedGeographicArea	= 5,
	VAM_PDU_Descriptions_VruEnvironment_max	= 255
} e_VAM_PDU_Descriptions_VruEnvironment;

/* VAM-PDU-Descriptions_VruEnvironment */
typedef long	 VAM_PDU_Descriptions_VruEnvironment_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VAM_PDU_Descriptions_VruEnvironment_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VAM_PDU_Descriptions_VruEnvironment;
extern const asn_INTEGER_specifics_t asn_SPC_VAM_PDU_Descriptions_VruEnvironment_specs_1;
asn_struct_free_f VAM_PDU_Descriptions_VruEnvironment_free;
asn_struct_print_f VAM_PDU_Descriptions_VruEnvironment_print;
asn_constr_check_f VAM_PDU_Descriptions_VruEnvironment_constraint;
ber_type_decoder_f VAM_PDU_Descriptions_VruEnvironment_decode_ber;
der_type_encoder_f VAM_PDU_Descriptions_VruEnvironment_encode_der;
xer_type_decoder_f VAM_PDU_Descriptions_VruEnvironment_decode_xer;
xer_type_encoder_f VAM_PDU_Descriptions_VruEnvironment_encode_xer;
jer_type_encoder_f VAM_PDU_Descriptions_VruEnvironment_encode_jer;
oer_type_decoder_f VAM_PDU_Descriptions_VruEnvironment_decode_oer;
oer_type_encoder_f VAM_PDU_Descriptions_VruEnvironment_encode_oer;
per_type_decoder_f VAM_PDU_Descriptions_VruEnvironment_decode_uper;
per_type_encoder_f VAM_PDU_Descriptions_VruEnvironment_encode_uper;
per_type_decoder_f VAM_PDU_Descriptions_VruEnvironment_decode_aper;
per_type_encoder_f VAM_PDU_Descriptions_VruEnvironment_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VAM_PDU_Descriptions_VruEnvironment_H_ */
#include "asn_internal.h"
