/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TIS-TPG-Transactions-Descriptions"
 * 	found in "asn1/TIS-TPG-Transactions-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VehicleSpecificData_H_
#define	_VehicleSpecificData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PressureConfiguration.h"
#include "TyreData.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleSpecificData */
typedef struct VehicleSpecificData {
	PressureConfiguration_t	 currentVehicleConfiguration;
	TyreData_t	 frontLeftTyreData;
	TyreData_t	 frontRightTyreData;
	TyreData_t	 rearLeftTyreData;
	TyreData_t	 rearRightTyreData;
	TyreData_t	 spareTyreData;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSpecificData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSpecificData;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleSpecificData_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleSpecificData_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSpecificData_H_ */
#include "asn_internal.h"
