/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "asn1/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VehicleAutomationLevel_H_
#define	_VehicleAutomationLevel_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleAutomationLevel {
	VehicleAutomationLevel_unavailable	= 0,
	VehicleAutomationLevel_saeLevel1	= 1,
	VehicleAutomationLevel_saeLevel2	= 2,
	VehicleAutomationLevel_saeLevel3	= 3,
	VehicleAutomationLevel_saeLevel4	= 4,
	VehicleAutomationLevel_saeLevel5	= 5
} e_VehicleAutomationLevel;

/* VehicleAutomationLevel */
typedef long	 VehicleAutomationLevel_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehicleAutomationLevel_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehicleAutomationLevel;
extern const asn_INTEGER_specifics_t asn_SPC_VehicleAutomationLevel_specs_1;
asn_struct_free_f VehicleAutomationLevel_free;
asn_struct_print_f VehicleAutomationLevel_print;
asn_constr_check_f VehicleAutomationLevel_constraint;
ber_type_decoder_f VehicleAutomationLevel_decode_ber;
der_type_encoder_f VehicleAutomationLevel_encode_der;
xer_type_decoder_f VehicleAutomationLevel_decode_xer;
xer_type_encoder_f VehicleAutomationLevel_encode_xer;
oer_type_decoder_f VehicleAutomationLevel_decode_oer;
oer_type_encoder_f VehicleAutomationLevel_encode_oer;
per_type_decoder_f VehicleAutomationLevel_decode_uper;
per_type_encoder_f VehicleAutomationLevel_encode_uper;
per_type_decoder_f VehicleAutomationLevel_decode_aper;
per_type_encoder_f VehicleAutomationLevel_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleAutomationLevel_H_ */
#include "asn_internal.h"
