/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "asn1/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VehicleCurrentState_H_
#define	_VehicleCurrentState_H_


#include "asn_application.h"

/* Including external dependencies */
#include "McmGenericCurrentState.h"
#include "VehicleAutomationState.h"
#include "ETSI-ITS-CDD_Speed.h"
#include "ETSI-ITS-CDD_Heading.h"
#include "ETSI-ITS-CDD_LongitudinalAcceleration.h"
#include "VehicleSize.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleCurrentState */
typedef struct VehicleCurrentState {
	McmGenericCurrentState_t	 mcmGenericCurrentState;
	VehicleAutomationState_t	 vehicleAutomationState;
	ETSI_ITS_CDD_Speed_t	 speed;
	ETSI_ITS_CDD_Heading_t	 heading;
	ETSI_ITS_CDD_LongitudinalAcceleration_t	 longitudinalAcceleration;
	VehicleSize_t	 vehicleSize;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleCurrentState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleCurrentState;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleCurrentState_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleCurrentState_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleCurrentState_H_ */
#include "asn_internal.h"
