/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "asn1/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VehicleManoeuvreContainer_H_
#define	_VehicleManoeuvreContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "ManoeuvreCoordinationConcept.h"
#include "ManoeuvreCoordinationRational.h"
#include "ManoeuvreExecutionCoordinationStep.h"
#include "Trajectory.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VehicleAutomationState;
struct ManoeuvreAdviceContainer;

/* VehicleManoeuvreContainer */
typedef struct VehicleManoeuvreContainer {
	long	 manoeuvreId;
	ManoeuvreCoordinationConcept_t	 manoeuvreCoordinationConcept;
	ManoeuvreCoordinationRational_t	 manoeuvreCoordinationRational;
	ManoeuvreExecutionCoordinationStep_t	 manoeuvreExecutionCoordinationStep;
	struct VehicleAutomationState	*vehicleAutomationState;	/* OPTIONAL */
	Trajectory_t	 vehicleReferenceTrajectory;
	struct ManoeuvreAdviceContainer	*manoeuvreAdviceContainer;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleManoeuvreContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleManoeuvreContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleManoeuvreContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleManoeuvreContainer_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VehicleAutomationState.h"
#include "ManoeuvreAdviceContainer.h"

#endif	/* _VehicleManoeuvreContainer_H_ */
#include "asn_internal.h"
