/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "asn1/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VehicleSize_H_
#define	_VehicleSize_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_Iso3833VehicleType.h"
#include "ETSI-ITS-CDD_SpecialTransportType.h"
#include "ETSI-ITS-CDD_VehicleLength.h"
#include "ETSI-ITS-CDD_VehicleWidth.h"
#include "ETSI-ITS-CDD_VehicleHeight.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleSize */
typedef struct VehicleSize {
	ETSI_ITS_CDD_Iso3833VehicleType_t	 vehicleType;
	ETSI_ITS_CDD_SpecialTransportType_t	*vehicleTransportedGoods;	/* OPTIONAL */
	ETSI_ITS_CDD_VehicleLength_t	 vehicleLenth;
	ETSI_ITS_CDD_VehicleWidth_t	 vehicleWidth;
	ETSI_ITS_CDD_VehicleHeight_t	 vehicleHeight;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSize_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSize;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleSize_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleSize_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSize_H_ */
#include "asn_internal.h"
