/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Description"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_WrappedExtensionContainers_H_
#define	_WrappedExtensionContainers_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct WrappedExtensionContainer;

/* WrappedExtensionContainers */
typedef struct WrappedExtensionContainers {
	A_SEQUENCE_OF(struct WrappedExtensionContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WrappedExtensionContainers_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WrappedExtensionContainers;
extern asn_SET_OF_specifics_t asn_SPC_WrappedExtensionContainers_specs_1;
extern asn_TYPE_member_t asn_MBR_WrappedExtensionContainers_1[1];
extern asn_per_constraints_t asn_PER_type_WrappedExtensionContainers_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "WrappedExtensionContainer.h"

#endif	/* _WrappedExtensionContainers_H_ */
#include "asn_internal.h"
