/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IMZM-PDU-Descriptions"
 * 	found in "asn1/IMZM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ZoneDefinition_H_
#define	_ZoneDefinition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Latitude.h"
#include "Longitude.h"
#include "ProtectedZoneRadius.h"
#include "ProtectedZoneID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InterferenceManagementZoneShape;

/* ZoneDefinition */
typedef struct ZoneDefinition {
	Latitude_t	 interferenceManagementZoneLatitude;
	Longitude_t	 interferenceManagementZoneLongitude;
	ProtectedZoneRadius_t	*interferenceManagementZoneRadius;	/* OPTIONAL */
	ProtectedZoneID_t	*interferenceManagementZoneID;	/* OPTIONAL */
	struct InterferenceManagementZoneShape	*interferenceManagementZoneShape;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ZoneDefinition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ZoneDefinition;
extern asn_SEQUENCE_specifics_t asn_SPC_ZoneDefinition_specs_1;
extern asn_TYPE_member_t asn_MBR_ZoneDefinition_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InterferenceManagementZoneShape.h"

#endif	/* _ZoneDefinition_H_ */
#include "asn_internal.h"
