MCM-PDU-Descriptions {
itu-t (0) identified-organization (4) etsi (0) itsDomain (5) wg1 (1) en (300000) mcm (2) version (1) 
}

DEFINITIONS AUTOMATIC TAGS ::=

BEGIN

IMPORTS
    ItsPduHeader, Position, Speed, Heading, Acceleration, VehicleRole, VehicleLength, VehicleWidth, ManeuverType, ManeuverStatus, TrafficRule, TimeOfOccurrence, EventPriority, Latitude, Longitude,
    EmergencyStatus FROM ITS-Container {
        itu-t (0) identified-organization (4) etsi (0) itsDomain (5) wg1 (1) ts (102894) cdd (2) version (2) 
    }
    GenerationDeltaTime FROM CAM-PDU-Descriptions {
        itu-t (0) identified-organization (4) etsi (0) itsDomain (5) wg1 (1) en (302637) cam (2) version (2)
    };

-- The root data frame for Maneuver Coordination Messages

MCM ::= SEQUENCE {
    header ItsPduHeader,
    mcmParameter MCMParameter
}

MCMParameter ::= SEQUENCE { -- made by me not in the standard
    basicContainer BasicContainer,
    manoeuvresCoordinationContainer ManoeuvresCoordinationContainer,
    agreementSeekingContainer AgreementSeekingContainer OPTIONAL,
    prescriptiveContainer PrescriptiveContainer OPTIONAL,
    responseContainer ResponseContainer OPTIONAL
}


BasicContainer ::= SEQUENCE {             --  The basic container contains the DF and DEs which are identified here below.
    generationDeltaTime GenerationDeltaTime, -- Time corresponding to the time of the reference position considered as the time of generation
    typeOriginatingIT-S StationType,    -- Type of originating IT-S which is dessiminating the message
    latestGeographicPosition LatestGeographicPosition -- spatial coordinates of the ITS-S position at the time of MCM dissemination
}

LatestGeographicPosition ::= SEQUENCE { --This DF contains the spatial coordinates of the ITS-S position at the time of the MCM  dissemination.
    latitudeValue Latitude, -- This DE represents the absolute geographical latitude value of the originating ITS-S in  a WGS84 coordinate system
    longitudeValue Longitude, -- This DE represents the absolute geographical longitude value of the originating ITS-S in  a WGS84 coordinate system
    altitudeValue Altitude OPTIONAL -- This DE represents the absolute geographical altitude value of the originating ITS-S in  a WGS84 coordinate system
    }

ManoeuvresCoordinationContainer ::= SEQUENCE { --This container comprises information which are necessary for the management of the manoeuvres' coordination from their initiation until their end
    manoeuvresID ManoeuvresID, -- Unique identifier provided by the manoeuvres' coordination initiator
    manoeuvresCoordinationConcept ManoeuvresCoordinationConcept, -- Identification of the manoeuvres'coordination concept which is used by the originating ITS-S
    manoeuvresCoordinationStep ManoeuvresCoordinationStep -- Identification of the current step in a manoeuvres Coordination procress under evolution
}

ManoeuvresID ::= INTEGER (0..255) -- 1 millisecond unit

ManoeuvresCoordinationConcept ::= ENUMERATED { --This is the identification of the manoeuvres'coordination concept which is used by the originating ITS-S.  
    agreementSeekingRequest (0),
    agreementSeekingOffer (1), 
    prescriptiveInterception (2), 
    prescriptiveRoadSafety (3), 
    prescriptiveGlobalTrafficManagement (4), 
    prescriptiveLocalTrafficManagement (5) 
}

ManoeuvresCoordinationStep ::= ENUMERATED { --This is the identification of the current step in a manoeuvres Coordination procress under evolution
    startProcess(0),
    progressProcessAcceptance(1),
    cancelProcessDecline(2),
    cancelProcessNotUnderstood(3),
    cancelProcessErrorneousBehaviour(4),
    cancelProcessMisbehaviourDetected(5),
    processTermination(6)
}

AgreementSeekingContainer ::= SEQUENCE { --Data elements in this container are used to coordinate mobile objects manoeuvres following the agreement of the main relevant mobile objects
    mcmCategory MCMCategory, -- Category of the MCM message
    vehicleAutomationLevel VehicleAutomationLevel, -- Automation level of the vehicle
    vehicleReferenceTrajectory Trajectory, -- Reference trajectory of the vehicle
    vehiclerRequestedTrajectory Trajectory, -- Requested trajectory of the vehicle
    numberofTargetedVehicleManoeuvresCoordination NumberOfTargetedVehicleManoeuvresCoordination OPTIONAL, -- Number of targeted vehicle manoeuvres
    targetVehicleITS-SID StationID, -- Target vehicle ITS-S identifier
    targetVehicleAlternativeTrajectory Trajectory, -- Alternative trajectory of the target vehicle
    estimatedCostOriginating CooperationCost -- Estimated cost of the originating vehicle
}

MCMCategory ::= ENUMERATED { --Indicates the category of the Manoeuvres'  Coordination Message according to the manoeuvres' coordination process progression. 
    request (0),
    offer (1),
    response (2),
    progress (3),
    cancelation (4),
    termination (5)
}

VehicleAutomationLevel ::= ENUMERATED { --Indicates the current vehicle automation level.
    unavailable (0),
    saeLevel1 (1),
    saeLevel2 (2),
    saeLevel3 (3),
    saeLevel4 (4),
    saeLevel5 (5)
}

Trajectory ::= SEQUENCE { --Provides the predicted path of the vehicle trajectory (succession of intermediate points with their time of position)
    intermediatePoints SEQUENCE SIZE (1..10) OF IntermediatePoint, 
    longitudinalPosition SEQUENCE SIZE (1..11) OF Polynom, 
    lateralPosition SEQUENCE SIZE (1..11) OF Polynom, 
    headings SEQUENCE SIZE (1..11) OF Polynom
}

IntermediatePoint ::= CHOICE { --Several types of intermediate points are available with the choice left to originating ITS-S according to the local situation needing manoeuvres' coordination.  
    reference IntermediatePointReference, 
    lane IntermediatePointLane, 
    intersection IntermediatePointIntersection, 
    offroad IntermediatePointOffroad
}

Polynom ::= SEQUENCE{ --The X= S/T polynom enables the processing of the mobile object speed and then speed variation as well as the travelled distance during the delta time T
    coefficients SEQUENCE SIZE (1..6) OF PolynomCoefficient, 
    start PolynomStartX, 
    end PolynomEndX, 
    xOffset PolynomXOffset  
}

PolynomCoefficient ::= REAL --This is the coefficient of the polynom under consideration. 
    PolynomStartX ::= INTEGER (0..2097151) -- It is the spatial or time distance of the start intermediate point position for the considered polynom computation
    PolynomEndX ::= INTEGER (0..2097151) -- It is the spatial or time distance of the end intermediate point position for the considered polynom computation.
    PolynomXOffset ::= INTEGER (-8000000..8000000) -- It is the spatial or time distance travelled in reference to the previous intermediate point position 
    -- Basic types 
    LaneCount ::= INTEGER (1..16) -- Number of Lanes, 
    TimeOfPos ::= INTEGER (0..65535) -- Unit: 0.01 seconds, 
    Reason ::= ENUMERATED { 
    none (0), 
    laneOpening (1), 
    laneClosing (2), 
    laneChange (3)
    } 



IntermediatePointReference ::= SEQUENCE { --Provides the coordinates' position and velocity of the vehicle at the level of the considered intermediate point of reference. 
    referencePosition ReferencePosition,
    referenceHeading Heading,
    lane Lane,
    timeOfPos TimeOfPos
}

IntermediatePointLane ::= SEQUENCE {    --Provides the position of the vehicle in a lane and other data elements which may require a lane change. 
    lane Lane,
    reason Reason,
    timeOfPos TimeOfPos
}

IntermediatePointIntersection ::= SEQUENCE { --Provides the trajectory evolution of the vehicle at an intersection level. 
    exitLane SEQUENCE { 
    lanePosition LanePosition, 
    laneCount LaneCount 
}, 
    exitHeading Heading, 
    timeOfPosEntry TimeOfPos, -- time on the trajectory when the intersection will be entered, 
    timeOfPosExit TimeOfPos -- time on the trajectory when the intersection will be leaved, 
} 

IntermediatePointOffroad ::= SEQUENCE { --Provides the trajectory evolution of the vehicle when moving off road. 
    referencePosition ReferencePosition, 
    referenceHeading Heading, 
    timeOfPos TimeOfPos 
} 
 
Lane::= SEQUENCE {  --Provides data elements related to the road topography when the number of available lanes is changing
    lanePosition LanePosition, 
    laneCount LaneCount
} 

NumberOfTargetedVehicleManoeuvresCoordination ::= INTEGER (1..16)    --Provides the number of targeted vehicles which are simultaneously addressed to achive a manoeuvres' coordination.

TargetedVehicleManoeuvresCoordination::=CHOICE { --Provides information to target vehicles which are cooperating with a subject ITS-S to achieve the manoeuvres'coordination
    targetedVehicleITS-SID StationID,
    targetedVehicleAlternativeTrajectory TargetedVehicleAlternativeTrajectory,
    estimatedCostOriginatingITS-S CooperationCost
}

TargetedVehicleAlternativeTrajectory ::= SEQUENCE { -- The targeted vehicle proposed alternative trajectory for the support of the considered subject vehicle during the manoeuvres' coordination cooperation. 
    alternativeTrajectory Trajectory,
    lane Lane
}

CooperationCost ::= INTEGER {zero(0), oneThousandth(1) } (-1000..1000) --This is the estimated cooperation cost of the planned manoeuvres from the point of view of the MMC originating ITS-S  

PrescriptiveContainer ::= CHOICE { -- Data elements in this container are used to coordinate mobile objects manoeuvres from the ITS-S which obtained the prescriptive MC service special permission. 
    mcmCategory MCMCategory, -- Category of the MCM message
    prescriptionType PrescriptiveType, -- Type of prescription
    vehicleAutomationLevel VehicleAutomationLevel, -- Automation level of the vehicle
    vehicleReferenceTrajectory Trajectory, -- Reference trajectory of the vehicle
    numberOfTargetedVehicleManoeuvresCoordination NumberOfTargetedVehicleManoeuvresCoordination, -- Number of targeted vehicle manoeuvres
    targetVehicleITS-SID StationID, -- Target vehicle ITS-S identifier
    targetVehicleAlternativeTrajectory Trajectory -- Alternative trajectory of the target vehicle
}

PrescriptiveType ::= ENUMERATED { --Provides the type of prescription which is disseminated to relevant ITS-Ss in prescriptive MC.
    roadSafetyObjective (1), 
    vehicleInterceptionObjective (2), 
    globalTrafficManagementObjective (3), 
    localTrafficManagementObjective (4)
}

ResponseContainer ::= SEQUENCE { --Response of the targeted ITS-S to a cooperative manoeuvres' coordination received from an ITS-S which is supervising the manoeuvres' coordination cooperation process.
    mcmCategory MCMCategory, -- Category of the MCM message
    acceptabilityStatus AcceptabilityStatus, -- Acceptability status of the message
    vehicleReferenceTrajectory Trajectory, -- Reference trajectory of the vehicle
    vehicleAutomationLevel VehicleAutomationLevel, -- Automation level of the vehicle
    estimatedCooperationCost CooperationCost -- Estimated cooperation cost
}

AcceptabilityStatus ::= ENUMERATED { --Provides the acceptability status of the responding ITS-S relatively to the last received MCM.
    acceptation (1), 
    refuseRoadSafetyRisk (2), 
    refuseCooperationCostTooHight (3), 
    refuseMissbehaviourDetected (4), 
    refuseTrafficRulesNotRespected (5), 
    offeredRefused (6)
} 

END