/*
 * Generated by asn1c
 * From ASN.1 module "AVM-Commons"
 * 	found in "AVM-Commons.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#include "AvmE2EProtection.h"

asn_TYPE_member_t asn_MBR_Vanetza_ITS2_AvmE2EProtection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_AvmE2EProtection, length),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_UInt16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"length"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_AvmE2EProtection, rollingCounter),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_UInt16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"rollingCounter"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_AvmE2EProtection, dataID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_UInt32,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dataID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_AvmE2EProtection, crc32),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_UInt32,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"crc32"
		},
};
static const ber_tlv_tag_t asn_DEF_Vanetza_ITS2_AvmE2EProtection_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Vanetza_ITS2_AvmE2EProtection_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* length */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rollingCounter */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dataID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* crc32 */
};
asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_AvmE2EProtection_specs_1 = {
	sizeof(struct Vanetza_ITS2_AvmE2EProtection),
	offsetof(struct Vanetza_ITS2_AvmE2EProtection, _asn_ctx),
	asn_MAP_Vanetza_ITS2_AvmE2EProtection_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_AvmE2EProtection = {
	"AvmE2EProtection",
	"AvmE2EProtection",
	&asn_OP_SEQUENCE,
	asn_DEF_Vanetza_ITS2_AvmE2EProtection_tags_1,
	sizeof(asn_DEF_Vanetza_ITS2_AvmE2EProtection_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_AvmE2EProtection_tags_1[0]), /* 1 */
	asn_DEF_Vanetza_ITS2_AvmE2EProtection_tags_1,	/* Same as above */
	sizeof(asn_DEF_Vanetza_ITS2_AvmE2EProtection_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_AvmE2EProtection_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Vanetza_ITS2_AvmE2EProtection_1,
	4,	/* Elements count */
	&asn_SPC_Vanetza_ITS2_AvmE2EProtection_specs_1	/* Additional specs */
};

