/*
 * Generated by asn1c
 * From ASN.1 module "AVM-Commons"
 * 	found in "AVM-Commons.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_AvmE2EProtection_H_
#define	_Vanetza_ITS2_AvmE2EProtection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "UInt16.h"
#include "UInt32.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_ITS2_AvmE2EProtection */
typedef struct Vanetza_ITS2_AvmE2EProtection {
	Vanetza_ITS2_UInt16_t	 length;
	Vanetza_ITS2_UInt16_t	 rollingCounter;
	Vanetza_ITS2_UInt32_t	 dataID;
	Vanetza_ITS2_UInt32_t	 crc32;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_AvmE2EProtection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_AvmE2EProtection;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_AvmE2EProtection_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_AvmE2EProtection_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_AvmE2EProtection_H_ */
#include "asn_internal.h"
