/*
 * Generated by asn1c
 * From ASN.1 module "MVM-PDU-Descriptions"
 * 	found in "MVM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_BasicVehicleClassEnum_H_
#define	_Vanetza_ITS2_BasicVehicleClassEnum_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_BasicVehicleClassEnum {
	Vanetza_ITS2_BasicVehicleClassEnum_none	= 0,
	Vanetza_ITS2_BasicVehicleClassEnum_unknown	= 1,
	Vanetza_ITS2_BasicVehicleClassEnum_special	= 2,
	Vanetza_ITS2_BasicVehicleClassEnum_moto	= 3,
	Vanetza_ITS2_BasicVehicleClassEnum_car	= 4,
	Vanetza_ITS2_BasicVehicleClassEnum_carOther	= 5,
	Vanetza_ITS2_BasicVehicleClassEnum_bus	= 6,
	Vanetza_ITS2_BasicVehicleClassEnum_axleCnt2	= 7,
	Vanetza_ITS2_BasicVehicleClassEnum_axleCnt3	= 8,
	Vanetza_ITS2_BasicVehicleClassEnum_axleCnt4	= 9,
	Vanetza_ITS2_BasicVehicleClassEnum_axleCnt4Trailer	= 10,
	Vanetza_ITS2_BasicVehicleClassEnum_axleCnt5Trailer	= 11,
	Vanetza_ITS2_BasicVehicleClassEnum_axleCnt6Trailer	= 12,
	Vanetza_ITS2_BasicVehicleClassEnum_axleCnt5MultiTrailer	= 13,
	Vanetza_ITS2_BasicVehicleClassEnum_axleCnt6MultiTrailer	= 14,
	Vanetza_ITS2_BasicVehicleClassEnum_axleCnt7MultiTrailer	= 15
	/*
	 * Enumeration is extensible
	 */
} e_Vanetza_ITS2_BasicVehicleClassEnum;

/* Vanetza_ITS2_BasicVehicleClassEnum */
typedef long	 Vanetza_ITS2_BasicVehicleClassEnum_t;

/* Implementation */
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_BasicVehicleClassEnum_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_BasicVehicleClassEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_BasicVehicleClassEnum;
extern const asn_INTEGER_specifics_t asn_SPC_Vanetza_ITS2_BasicVehicleClassEnum_specs_1;
asn_struct_free_f Vanetza_ITS2_BasicVehicleClassEnum_free;
asn_struct_print_f Vanetza_ITS2_BasicVehicleClassEnum_print;
asn_constr_check_f Vanetza_ITS2_BasicVehicleClassEnum_constraint;
ber_type_decoder_f Vanetza_ITS2_BasicVehicleClassEnum_decode_ber;
der_type_encoder_f Vanetza_ITS2_BasicVehicleClassEnum_encode_der;
xer_type_decoder_f Vanetza_ITS2_BasicVehicleClassEnum_decode_xer;
xer_type_encoder_f Vanetza_ITS2_BasicVehicleClassEnum_encode_xer;
jer_type_encoder_f Vanetza_ITS2_BasicVehicleClassEnum_encode_jer;
oer_type_decoder_f Vanetza_ITS2_BasicVehicleClassEnum_decode_oer;
oer_type_encoder_f Vanetza_ITS2_BasicVehicleClassEnum_encode_oer;
per_type_decoder_f Vanetza_ITS2_BasicVehicleClassEnum_decode_uper;
per_type_encoder_f Vanetza_ITS2_BasicVehicleClassEnum_encode_uper;
per_type_decoder_f Vanetza_ITS2_BasicVehicleClassEnum_decode_aper;
per_type_encoder_f Vanetza_ITS2_BasicVehicleClassEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_BasicVehicleClassEnum_H_ */
#include "asn_internal.h"
