/*
 * Generated by asn1c
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "MIM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_ControlPoint_H_
#define	_Vanetza_ITS2_ControlPoint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "HighResCurvature.h"
#include "ControlParameter.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_ITS2_ControlPoint */
typedef struct Vanetza_ITS2_ControlPoint {
	Vanetza_ITS2_HighResCurvature_t	 curvature;
	Vanetza_ITS2_ControlParameter_t	 controlParameter;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_ControlPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_ControlPoint;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_ControlPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_ControlPoint_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_ControlPoint_H_ */
#include "asn_internal.h"
