/*
 * Generated by asn1c
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "MIM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_ControlParameter_H_
#define	_Vanetza_ITS2_ControlParameter_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ControlAcceleration.h"
#include "ControlVelocity.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_ControlParameter_PR {
	Vanetza_ITS2_ControlParameter_PR_NOTHING,	/* No components present */
	Vanetza_ITS2_ControlParameter_PR_controlAcceleration,
	Vanetza_ITS2_ControlParameter_PR_controlVelocity
} Vanetza_ITS2_ControlParameter_PR;

/* Vanetza_ITS2_ControlParameter */
typedef struct Vanetza_ITS2_ControlParameter {
	Vanetza_ITS2_ControlParameter_PR present;
	union Vanetza_ITS2_ControlParameter_u {
		Vanetza_ITS2_ControlAcceleration_t	 controlAcceleration;
		Vanetza_ITS2_ControlVelocity_t	 controlVelocity;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_ControlParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_ControlParameter;
extern asn_CHOICE_specifics_t asn_SPC_Vanetza_ITS2_ControlParameter_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_ControlParameter_1[2];
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_ControlParameter_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_ControlParameter_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_ControlParameter_H_ */
#include "asn_internal.h"
