/*
 * Generated by asn1c
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "MIM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_DriveCommand_H_
#define	_Vanetza_ITS2_DriveCommand_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DriveCommandActionEnum.h"
#include "TerminateReasonEnum.h"
#include "GearEnum.h"
#include "DirectionIndicatorEnum.h"
#include "ParkingBrakeRequestEnum.h"
#include "MotorSystemEnum.h"
#include "EmergencyStopEnum.h"
#include "InterlockEnum.h"
#include "VehicleHornRequestEnum.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_ITS2_DriveCommand */
typedef struct Vanetza_ITS2_DriveCommand {
	Vanetza_ITS2_DriveCommandActionEnum_t	 driveCommandAction;
	Vanetza_ITS2_TerminateReasonEnum_t	 terminateReason;
	Vanetza_ITS2_GearEnum_t	*gearRequest;	/* OPTIONAL */
	Vanetza_ITS2_DirectionIndicatorEnum_t	*directionIndicatorRequest;	/* OPTIONAL */
	Vanetza_ITS2_ParkingBrakeRequestEnum_t	*parkingBrakeRequest;	/* OPTIONAL */
	Vanetza_ITS2_MotorSystemEnum_t	*motorSystemRequest;	/* OPTIONAL */
	Vanetza_ITS2_EmergencyStopEnum_t	*emergencyStopRequest;	/* OPTIONAL */
	Vanetza_ITS2_InterlockEnum_t	*interlockRequest;	/* OPTIONAL */
	Vanetza_ITS2_VehicleHornRequestEnum_t	*hornRequest;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_DriveCommand_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_DriveCommand;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_DriveCommand_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_DriveCommand_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_DriveCommand_H_ */
#include "asn_internal.h"
