/*
 * Generated by asn1c
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "MIM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#include "EmergencyStopEnum.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_EmergencyStopEnum_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_Vanetza_ITS2_EmergencyStopEnum_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_Vanetza_ITS2_EmergencyStopEnum_value2enum_1[] = {
	{ 0,	8,	"inactive" },
	{ 1,	9,	"precharge" },
	{ 2,	6,	"active" },
	{ 3,	9,	"tempError" },
	{ 4,	7,	"suspend" }
};
static int asn_validate_Vanetza_ITS2_EmergencyStopEnum(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_Vanetza_ITS2_EmergencyStopEnum value = *(e_Vanetza_ITS2_EmergencyStopEnum*)sptr;
    switch(value) {
    case Vanetza_ITS2_EmergencyStopEnum_inactive:
    case Vanetza_ITS2_EmergencyStopEnum_precharge:
    case Vanetza_ITS2_EmergencyStopEnum_active:
    case Vanetza_ITS2_EmergencyStopEnum_tempError:
    case Vanetza_ITS2_EmergencyStopEnum_suspend:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_Vanetza_ITS2_EmergencyStopEnum_enum2value_1[] = {
	2,	/* active(2) */
	0,	/* inactive(0) */
	1,	/* precharge(1) */
	4,	/* suspend(4) */
	3	/* tempError(3) */
};
const asn_INTEGER_specifics_t asn_SPC_Vanetza_ITS2_EmergencyStopEnum_specs_1 = {
	asn_MAP_Vanetza_ITS2_EmergencyStopEnum_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_Vanetza_ITS2_EmergencyStopEnum_enum2value_1,	/* N => "tag"; sorted by N */
	5,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_Vanetza_ITS2_EmergencyStopEnum_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_EmergencyStopEnum = {
	"EmergencyStopEnum",
	"EmergencyStopEnum",
	&asn_OP_NativeEnumerated,
	asn_DEF_Vanetza_ITS2_EmergencyStopEnum_tags_1,
	sizeof(asn_DEF_Vanetza_ITS2_EmergencyStopEnum_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_EmergencyStopEnum_tags_1[0]), /* 1 */
	asn_DEF_Vanetza_ITS2_EmergencyStopEnum_tags_1,	/* Same as above */
	sizeof(asn_DEF_Vanetza_ITS2_EmergencyStopEnum_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_EmergencyStopEnum_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_Vanetza_ITS2_EmergencyStopEnum_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_Vanetza_ITS2_EmergencyStopEnum_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_Vanetza_ITS2_EmergencyStopEnum
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_Vanetza_ITS2_EmergencyStopEnum_specs_1	/* Additional specs */
};

