/*
 * Generated by asn1c
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_ManoeuvreCooperationGoal_H_
#define	_Vanetza_ITS2_ManoeuvreCooperationGoal_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_ManoeuvreCooperationGoal {
	Vanetza_ITS2_ManoeuvreCooperationGoal_vehicleInterception	= 0,
	Vanetza_ITS2_ManoeuvreCooperationGoal_roadSafety	= 1,
	Vanetza_ITS2_ManoeuvreCooperationGoal_humanHelth	= 2,
	Vanetza_ITS2_ManoeuvreCooperationGoal_emergencyIntervention	= 3,
	Vanetza_ITS2_ManoeuvreCooperationGoal_roadOperatorIntervention	= 4,
	Vanetza_ITS2_ManoeuvreCooperationGoal_localTrafficManagement	= 5,
	Vanetza_ITS2_ManoeuvreCooperationGoal_globalTrafficManagement	= 6
} e_Vanetza_ITS2_ManoeuvreCooperationGoal;

/* Vanetza_ITS2_ManoeuvreCooperationGoal */
typedef long	 Vanetza_ITS2_ManoeuvreCooperationGoal_t;

/* Implementation */
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_ManoeuvreCooperationGoal_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_ManoeuvreCooperationGoal_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_ManoeuvreCooperationGoal;
extern const asn_INTEGER_specifics_t asn_SPC_Vanetza_ITS2_ManoeuvreCooperationGoal_specs_1;
asn_struct_free_f Vanetza_ITS2_ManoeuvreCooperationGoal_free;
asn_struct_print_f Vanetza_ITS2_ManoeuvreCooperationGoal_print;
asn_constr_check_f Vanetza_ITS2_ManoeuvreCooperationGoal_constraint;
ber_type_decoder_f Vanetza_ITS2_ManoeuvreCooperationGoal_decode_ber;
der_type_encoder_f Vanetza_ITS2_ManoeuvreCooperationGoal_encode_der;
xer_type_decoder_f Vanetza_ITS2_ManoeuvreCooperationGoal_decode_xer;
xer_type_encoder_f Vanetza_ITS2_ManoeuvreCooperationGoal_encode_xer;
jer_type_encoder_f Vanetza_ITS2_ManoeuvreCooperationGoal_encode_jer;
oer_type_decoder_f Vanetza_ITS2_ManoeuvreCooperationGoal_decode_oer;
oer_type_encoder_f Vanetza_ITS2_ManoeuvreCooperationGoal_encode_oer;
per_type_decoder_f Vanetza_ITS2_ManoeuvreCooperationGoal_decode_uper;
per_type_encoder_f Vanetza_ITS2_ManoeuvreCooperationGoal_encode_uper;
per_type_decoder_f Vanetza_ITS2_ManoeuvreCooperationGoal_decode_aper;
per_type_encoder_f Vanetza_ITS2_ManoeuvreCooperationGoal_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_ManoeuvreCooperationGoal_H_ */
#include "asn_internal.h"
