/*
 * Generated by asn1c
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_ManoeuvreCoordinationRational_H_
#define	_Vanetza_ITS2_ManoeuvreCoordinationRational_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ManoeuvreCooperationGoal.h"
#include "ManoeuvreCooperationCost.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_ManoeuvreCoordinationRational_PR {
	Vanetza_ITS2_ManoeuvreCoordinationRational_PR_NOTHING,	/* No components present */
	Vanetza_ITS2_ManoeuvreCoordinationRational_PR_manoeuvreCooperationGoal,
	Vanetza_ITS2_ManoeuvreCoordinationRational_PR_manoeuvreCooperationCost
} Vanetza_ITS2_ManoeuvreCoordinationRational_PR;

/* Vanetza_ITS2_ManoeuvreCoordinationRational */
typedef struct Vanetza_ITS2_ManoeuvreCoordinationRational {
	Vanetza_ITS2_ManoeuvreCoordinationRational_PR present;
	union Vanetza_ITS2_ManoeuvreCoordinationRational_u {
		Vanetza_ITS2_ManoeuvreCooperationGoal_t	 manoeuvreCooperationGoal;
		Vanetza_ITS2_ManoeuvreCooperationCost_t	 manoeuvreCooperationCost;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_ManoeuvreCoordinationRational_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_ManoeuvreCoordinationRational;
extern asn_CHOICE_specifics_t asn_SPC_Vanetza_ITS2_ManoeuvreCoordinationRational_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_ManoeuvreCoordinationRational_1[2];
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_ManoeuvreCoordinationRational_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_ManoeuvreCoordinationRational_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_ManoeuvreCoordinationRational_H_ */
#include "asn_internal.h"
