/*
 * Generated by asn1c
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "MIM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#include "MIMDataControlField.h"

#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_rollingCounterFromMvm __attribute__((weak, alias("asn_DEF_Vanetza_ITS2_rollingCounterFromMvm_4")));
#else
static asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_rollingCounterFromMvm_4;
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_rollingCounterFromMvm;
__attribute__((constructor)) static void asn_DEF_Vanetza_ITS2_rollingCounterFromMvm_4_alias_init(void) {
	asn_DEF_Vanetza_ITS2_rollingCounterFromMvm = asn_DEF_Vanetza_ITS2_rollingCounterFromMvm_4;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
static int
memb_Vanetza_ITS2_rollingCounterFromMvm_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size <= 10UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_rollingCounterFromMvm_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..10)) */};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_Vanetza_ITS2_rollingCounterFromMvm_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (SIZE(0..10)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_Vanetza_ITS2_rollingCounterFromMvm_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..10)) */};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_Vanetza_ITS2_rollingCounterFromMvm_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (SIZE(0..10)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_Vanetza_ITS2_rollingCounterFromMvm_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Vanetza_ITS2_RollingCounter,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_Vanetza_ITS2_rollingCounterFromMvm_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_Vanetza_ITS2_rollingCounterFromMvm_specs_4 = {
	sizeof(struct Vanetza_ITS2_MIMDataControlField__rollingCounterFromMvm),
	offsetof(struct Vanetza_ITS2_MIMDataControlField__rollingCounterFromMvm, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_rollingCounterFromMvm_4 = {
	"rollingCounterFromMvm",
	"rollingCounterFromMvm",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_Vanetza_ITS2_rollingCounterFromMvm_tags_4,
	sizeof(asn_DEF_Vanetza_ITS2_rollingCounterFromMvm_tags_4)
		/sizeof(asn_DEF_Vanetza_ITS2_rollingCounterFromMvm_tags_4[0]) - 1, /* 1 */
	asn_DEF_Vanetza_ITS2_rollingCounterFromMvm_tags_4,	/* Same as above */
	sizeof(asn_DEF_Vanetza_ITS2_rollingCounterFromMvm_tags_4)
		/sizeof(asn_DEF_Vanetza_ITS2_rollingCounterFromMvm_tags_4[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_Vanetza_ITS2_rollingCounterFromMvm_constr_4,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_Vanetza_ITS2_rollingCounterFromMvm_constr_4,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_Vanetza_ITS2_rollingCounterFromMvm_4,
	1,	/* Single element */
	&asn_SPC_Vanetza_ITS2_rollingCounterFromMvm_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Vanetza_ITS2_MIMDataControlField_1[] = {
	{ ATF_POINTER, 2, offsetof(struct Vanetza_ITS2_MIMDataControlField, checksum),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_UInt32,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"checksum"
		},
	{ ATF_POINTER, 1, offsetof(struct Vanetza_ITS2_MIMDataControlField, mimGenerationTime),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_TimestampIts,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"mimGenerationTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_MIMDataControlField, rollingCounterFromMvm),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_Vanetza_ITS2_rollingCounterFromMvm,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_Vanetza_ITS2_rollingCounterFromMvm_constr_4,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_Vanetza_ITS2_rollingCounterFromMvm_constr_4,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_Vanetza_ITS2_rollingCounterFromMvm_constraint_1
		},
		0, 0, /* No default value */
		"rollingCounterFromMvm"
		},
	{ ATF_POINTER, 1, offsetof(struct Vanetza_ITS2_MIMDataControlField, proprietaryExtensionField),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_ProprietaryExtensionField,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"proprietaryExtensionField"
		},
};
static const int asn_MAP_Vanetza_ITS2_MIMDataControlField_oms_1[] = { 0, 1, 3 };
static const ber_tlv_tag_t asn_DEF_Vanetza_ITS2_MIMDataControlField_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Vanetza_ITS2_MIMDataControlField_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* checksum */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mimGenerationTime */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* rollingCounterFromMvm */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* proprietaryExtensionField */
};
asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_MIMDataControlField_specs_1 = {
	sizeof(struct Vanetza_ITS2_MIMDataControlField),
	offsetof(struct Vanetza_ITS2_MIMDataControlField, _asn_ctx),
	asn_MAP_Vanetza_ITS2_MIMDataControlField_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_Vanetza_ITS2_MIMDataControlField_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_MIMDataControlField = {
	"MIMDataControlField",
	"MIMDataControlField",
	&asn_OP_SEQUENCE,
	asn_DEF_Vanetza_ITS2_MIMDataControlField_tags_1,
	sizeof(asn_DEF_Vanetza_ITS2_MIMDataControlField_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_MIMDataControlField_tags_1[0]), /* 1 */
	asn_DEF_Vanetza_ITS2_MIMDataControlField_tags_1,	/* Same as above */
	sizeof(asn_DEF_Vanetza_ITS2_MIMDataControlField_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_MIMDataControlField_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Vanetza_ITS2_MIMDataControlField_1,
	4,	/* Elements count */
	&asn_SPC_Vanetza_ITS2_MIMDataControlField_specs_1	/* Additional specs */
};

