/*
 * Generated by asn1c
 * From ASN.1 module "AVM-Commons"
 * 	found in "AVM-Commons.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#include "MotorSystemEnum.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_MotorSystemEnum_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_Vanetza_ITS2_MotorSystemEnum_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_Vanetza_ITS2_MotorSystemEnum_value2enum_1[] = {
	{ 0,	3,	"off" },
	{ 1,	2,	"on" },
	{ 2,	7,	"unknown" }
};
static int asn_validate_Vanetza_ITS2_MotorSystemEnum(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_Vanetza_ITS2_MotorSystemEnum value = *(e_Vanetza_ITS2_MotorSystemEnum*)sptr;
    switch(value) {
    case Vanetza_ITS2_MotorSystemEnum_off:
    case Vanetza_ITS2_MotorSystemEnum_on:
    case Vanetza_ITS2_MotorSystemEnum_unknown:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_Vanetza_ITS2_MotorSystemEnum_enum2value_1[] = {
	0,	/* off(0) */
	1,	/* on(1) */
	2	/* unknown(2) */
};
const asn_INTEGER_specifics_t asn_SPC_Vanetza_ITS2_MotorSystemEnum_specs_1 = {
	asn_MAP_Vanetza_ITS2_MotorSystemEnum_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_Vanetza_ITS2_MotorSystemEnum_enum2value_1,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_Vanetza_ITS2_MotorSystemEnum_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_MotorSystemEnum = {
	"MotorSystemEnum",
	"MotorSystemEnum",
	&asn_OP_NativeEnumerated,
	asn_DEF_Vanetza_ITS2_MotorSystemEnum_tags_1,
	sizeof(asn_DEF_Vanetza_ITS2_MotorSystemEnum_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_MotorSystemEnum_tags_1[0]), /* 1 */
	asn_DEF_Vanetza_ITS2_MotorSystemEnum_tags_1,	/* Same as above */
	sizeof(asn_DEF_Vanetza_ITS2_MotorSystemEnum_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_MotorSystemEnum_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_Vanetza_ITS2_MotorSystemEnum_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_Vanetza_ITS2_MotorSystemEnum_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_Vanetza_ITS2_MotorSystemEnum
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_Vanetza_ITS2_MotorSystemEnum_specs_1	/* Additional specs */
};

