/*
 * Generated by asn1c
 * From ASN.1 module "MVM-PDU-Descriptions"
 * 	found in "MVM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_Mvm_H_
#define	_Vanetza_ITS2_Mvm_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_MVMDataControlField;
struct Vanetza_ITS2_SystemManagementData;
struct Vanetza_ITS2_VehicleState;
struct Vanetza_ITS2_VidResponse;
struct Vanetza_ITS2_SafetyTimeSyncResponse;
struct Vanetza_ITS2_SafeVehicleTypeConfirmation;
struct Vanetza_ITS2_VehicleError;
struct Vanetza_ITS2_VehicleSafetyFeedback;
struct Vanetza_ITS2_VehicleProperties;

/* Vanetza_ITS2_Mvm */
typedef struct Vanetza_ITS2_Mvm {
	struct Vanetza_ITS2_MVMDataControlField	*mvmDataControlField;	/* OPTIONAL */
	struct Vanetza_ITS2_SystemManagementData	*systemManagementData;	/* OPTIONAL */
	struct Vanetza_ITS2_VehicleState	*vehicleState;	/* OPTIONAL */
	struct Vanetza_ITS2_VidResponse	*vidResponse;	/* OPTIONAL */
	struct Vanetza_ITS2_SafetyTimeSyncResponse	*safetyTimeSyncResponse;	/* OPTIONAL */
	struct Vanetza_ITS2_SafeVehicleTypeConfirmation	*safeVehicleTypeConfirmation;	/* OPTIONAL */
	struct Vanetza_ITS2_VehicleError	*vehicleError;	/* OPTIONAL */
	struct Vanetza_ITS2_VehicleSafetyFeedback	*vehicleSafetyFeedback;	/* OPTIONAL */
	struct Vanetza_ITS2_VehicleProperties	*vehicleProperties;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_Mvm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_Mvm;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_Mvm_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_Mvm_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MVMDataControlField.h"
#include "SystemManagementData.h"
#include "VehicleState.h"
#include "VidResponse.h"
#include "SafetyTimeSyncResponse.h"
#include "SafeVehicleTypeConfirmation.h"
#include "VehicleError.h"
#include "VehicleSafetyFeedback.h"
#include "VehicleProperties.h"

#endif	/* _Vanetza_ITS2_Mvm_H_ */
#include "asn_internal.h"
