/*
 * Generated by asn1c
 * From ASN.1 module "MVM-PDU-Descriptions"
 * 	found in "MVM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_MVM_H_
#define	_Vanetza_ITS2_MVM_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ItsPduHeader.h"
#include "AvmE2EProtection.h"
#include "Mvm.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_ITS2_MVM */
typedef struct Vanetza_ITS2_MVM {
	Vanetza_ITS2_ItsPduHeader_t	 header;
	Vanetza_ITS2_AvmE2EProtection_t	 e2eProtection;
	Vanetza_ITS2_Mvm_t	 mvm;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_MVM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_MVM;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_MVM_H_ */
#include "asn_internal.h"
