/*
 * Generated by asn1c
 * From ASN.1 module "MVM-PDU-Descriptions"
 * 	found in "MVM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#include "MVMDataControlField.h"

#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_rollingCounterFromMim __attribute__((weak, alias("asn_DEF_Vanetza_ITS2_rollingCounterFromMim_3")));
#else
static asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_rollingCounterFromMim_3;
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_rollingCounterFromMim;
__attribute__((constructor)) static void asn_DEF_Vanetza_ITS2_rollingCounterFromMim_3_alias_init(void) {
	asn_DEF_Vanetza_ITS2_rollingCounterFromMim = asn_DEF_Vanetza_ITS2_rollingCounterFromMim_3;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
static int
memb_Vanetza_ITS2_rollingCounterFromMim_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size <= 10UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_rollingCounterFromMim_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..10)) */};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_Vanetza_ITS2_rollingCounterFromMim_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (SIZE(0..10)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_Vanetza_ITS2_rollingCounterFromMim_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..10)) */};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_Vanetza_ITS2_rollingCounterFromMim_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (SIZE(0..10)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_Vanetza_ITS2_rollingCounterFromMim_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Vanetza_ITS2_RollingCounter,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_Vanetza_ITS2_rollingCounterFromMim_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_Vanetza_ITS2_rollingCounterFromMim_specs_3 = {
	sizeof(struct Vanetza_ITS2_MVMDataControlField__rollingCounterFromMim),
	offsetof(struct Vanetza_ITS2_MVMDataControlField__rollingCounterFromMim, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_rollingCounterFromMim_3 = {
	"rollingCounterFromMim",
	"rollingCounterFromMim",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_Vanetza_ITS2_rollingCounterFromMim_tags_3,
	sizeof(asn_DEF_Vanetza_ITS2_rollingCounterFromMim_tags_3)
		/sizeof(asn_DEF_Vanetza_ITS2_rollingCounterFromMim_tags_3[0]) - 1, /* 1 */
	asn_DEF_Vanetza_ITS2_rollingCounterFromMim_tags_3,	/* Same as above */
	sizeof(asn_DEF_Vanetza_ITS2_rollingCounterFromMim_tags_3)
		/sizeof(asn_DEF_Vanetza_ITS2_rollingCounterFromMim_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_Vanetza_ITS2_rollingCounterFromMim_constr_3,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_Vanetza_ITS2_rollingCounterFromMim_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_Vanetza_ITS2_rollingCounterFromMim_3,
	1,	/* Single element */
	&asn_SPC_Vanetza_ITS2_rollingCounterFromMim_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Vanetza_ITS2_MVMDataControlField_1[] = {
	{ ATF_POINTER, 1, offsetof(struct Vanetza_ITS2_MVMDataControlField, mvmGenerationTime),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_TimestampIts,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"mvmGenerationTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_MVMDataControlField, rollingCounterFromMim),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_Vanetza_ITS2_rollingCounterFromMim,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_Vanetza_ITS2_rollingCounterFromMim_constr_3,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_Vanetza_ITS2_rollingCounterFromMim_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_Vanetza_ITS2_rollingCounterFromMim_constraint_1
		},
		0, 0, /* No default value */
		"rollingCounterFromMim"
		},
	{ ATF_POINTER, 1, offsetof(struct Vanetza_ITS2_MVMDataControlField, proprietaryExtensionField),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_ProprietaryExtensionField,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"proprietaryExtensionField"
		},
};
static const int asn_MAP_Vanetza_ITS2_MVMDataControlField_oms_1[] = { 0, 2 };
static const ber_tlv_tag_t asn_DEF_Vanetza_ITS2_MVMDataControlField_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Vanetza_ITS2_MVMDataControlField_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mvmGenerationTime */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rollingCounterFromMim */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* proprietaryExtensionField */
};
asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_MVMDataControlField_specs_1 = {
	sizeof(struct Vanetza_ITS2_MVMDataControlField),
	offsetof(struct Vanetza_ITS2_MVMDataControlField, _asn_ctx),
	asn_MAP_Vanetza_ITS2_MVMDataControlField_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_Vanetza_ITS2_MVMDataControlField_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_MVMDataControlField = {
	"MVMDataControlField",
	"MVMDataControlField",
	&asn_OP_SEQUENCE,
	asn_DEF_Vanetza_ITS2_MVMDataControlField_tags_1,
	sizeof(asn_DEF_Vanetza_ITS2_MVMDataControlField_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_MVMDataControlField_tags_1[0]), /* 1 */
	asn_DEF_Vanetza_ITS2_MVMDataControlField_tags_1,	/* Same as above */
	sizeof(asn_DEF_Vanetza_ITS2_MVMDataControlField_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_MVMDataControlField_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Vanetza_ITS2_MVMDataControlField_1,
	3,	/* Elements count */
	&asn_SPC_Vanetza_ITS2_MVMDataControlField_specs_1	/* Additional specs */
};

