/*
 * Generated by asn1c
 * From ASN.1 module "LHP-PMM-PDU-Descriptions"
 * 	found in "LHP-PMM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_PmmContainer_H_
#define	_Vanetza_ITS2_PmmContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PlatoonID.h"
#include "PmmType.h"
#include "PmmPayloadChoice.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_PmmReservedContainer;

/* Vanetza_ITS2_PmmContainer */
typedef struct Vanetza_ITS2_PmmContainer {
	Vanetza_ITS2_PlatoonID_t	 platoonId;
	Vanetza_ITS2_PmmType_t	 pmmType;
	Vanetza_ITS2_PmmPayloadChoice_t	 payload;
	struct Vanetza_ITS2_PmmReservedContainer	*reservedContainer;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_PmmContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_PmmContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_PmmContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_PmmContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PmmReservedContainer.h"

#endif	/* _Vanetza_ITS2_PmmContainer_H_ */
#include "asn_internal.h"
