/*
 * Generated by asn1c
 * From ASN.1 module "LHP-PMM-PDU-Descriptions"
 * 	found in "LHP-PMM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_PmmPayloadChoice_H_
#define	_Vanetza_ITS2_PmmPayloadChoice_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "ConnectivityReport.h"
#include "VlAssignment.h"
#include "FollowerAssignment.h"
#include "Acknowledgement.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_PmmPayloadChoice_PR {
	Vanetza_ITS2_PmmPayloadChoice_PR_NOTHING,	/* No components present */
	Vanetza_ITS2_PmmPayloadChoice_PR_connectivityRequest,
	Vanetza_ITS2_PmmPayloadChoice_PR_connectivityReport,
	Vanetza_ITS2_PmmPayloadChoice_PR_vlAssignment,
	Vanetza_ITS2_PmmPayloadChoice_PR_followerAssignment,
	Vanetza_ITS2_PmmPayloadChoice_PR_acknowledgement
	/* Extensions may appear below */
	
} Vanetza_ITS2_PmmPayloadChoice_PR;

/* Vanetza_ITS2_PmmPayloadChoice */
typedef struct Vanetza_ITS2_PmmPayloadChoice {
	Vanetza_ITS2_PmmPayloadChoice_PR present;
	union Vanetza_ITS2_PmmPayloadChoice_u {
		NULL_t	 connectivityRequest;
		Vanetza_ITS2_ConnectivityReport_t	 connectivityReport;
		Vanetza_ITS2_VlAssignment_t	 vlAssignment;
		Vanetza_ITS2_FollowerAssignment_t	 followerAssignment;
		Vanetza_ITS2_Acknowledgement_t	 acknowledgement;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_PmmPayloadChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_PmmPayloadChoice;
extern asn_CHOICE_specifics_t asn_SPC_Vanetza_ITS2_PmmPayloadChoice_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_PmmPayloadChoice_1[5];
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_PmmPayloadChoice_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_PmmPayloadChoice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_PmmPayloadChoice_H_ */
#include "asn_internal.h"
