/*
 * Generated by asn1c
 * From ASN.1 module "LHP-PMM-PDU-Descriptions"
 * 	found in "LHP-PMM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_PmmType_H_
#define	_Vanetza_ITS2_PmmType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_ITS2_PmmType */
typedef long	 Vanetza_ITS2_PmmType_t;

/* Implementation */
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_PmmType_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_PmmType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_PmmType;
asn_struct_free_f Vanetza_ITS2_PmmType_free;
asn_struct_print_f Vanetza_ITS2_PmmType_print;
asn_constr_check_f Vanetza_ITS2_PmmType_constraint;
ber_type_decoder_f Vanetza_ITS2_PmmType_decode_ber;
der_type_encoder_f Vanetza_ITS2_PmmType_encode_der;
xer_type_decoder_f Vanetza_ITS2_PmmType_decode_xer;
xer_type_encoder_f Vanetza_ITS2_PmmType_encode_xer;
jer_type_encoder_f Vanetza_ITS2_PmmType_encode_jer;
oer_type_decoder_f Vanetza_ITS2_PmmType_decode_oer;
oer_type_encoder_f Vanetza_ITS2_PmmType_encode_oer;
per_type_decoder_f Vanetza_ITS2_PmmType_decode_uper;
per_type_encoder_f Vanetza_ITS2_PmmType_encode_uper;
per_type_decoder_f Vanetza_ITS2_PmmType_decode_aper;
per_type_encoder_f Vanetza_ITS2_PmmType_encode_aper;
#define Vanetza_ITS2_PmmType_connectivityRequest	((Vanetza_ITS2_PmmType_t)0)
#define Vanetza_ITS2_PmmType_connectivityReport	((Vanetza_ITS2_PmmType_t)1)
#define Vanetza_ITS2_PmmType_vlAssignment	((Vanetza_ITS2_PmmType_t)2)
#define Vanetza_ITS2_PmmType_followerAssignment	((Vanetza_ITS2_PmmType_t)3)
#define Vanetza_ITS2_PmmType_acknowledgement	((Vanetza_ITS2_PmmType_t)4)

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_PmmType_H_ */
#include "asn_internal.h"
