/*
 * Generated by asn1c
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_ResponseContainer_H_
#define	_Vanetza_ITS2_ResponseContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ManouevreResponse.h"
#include "DeclineReason.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_ListOfSubmanoeuvreDescriptionsContainer;

/* Vanetza_ITS2_ResponseContainer */
typedef struct Vanetza_ITS2_ResponseContainer {
	Vanetza_ITS2_ManouevreResponse_t	 manouevreResponse;
	Vanetza_ITS2_DeclineReason_t	*declineReason;	/* OPTIONAL */
	struct Vanetza_ITS2_ListOfSubmanoeuvreDescriptionsContainer	*submaneuvres;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_ResponseContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_ResponseContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_ResponseContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_ResponseContainer_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ListOfSubmanoeuvreDescriptionsContainer.h"

#endif	/* _Vanetza_ITS2_ResponseContainer_H_ */
#include "asn_internal.h"
