/*
 * Generated by asn1c
 * From ASN.1 module "AVM-Commons"
 * 	found in "AVM-Commons.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_SafetyViolationsEnum_H_
#define	_Vanetza_ITS2_SafetyViolationsEnum_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_SafetyViolationsEnum {
	Vanetza_ITS2_SafetyViolationsEnum_noViolation	= 0,
	Vanetza_ITS2_SafetyViolationsEnum_noDrivingPermissionReceived	= 1,
	Vanetza_ITS2_SafetyViolationsEnum_lastDrivingPermissionTooOld	= 2,
	Vanetza_ITS2_SafetyViolationsEnum_crcViolationClockSyncRequest	= 3,
	Vanetza_ITS2_SafetyViolationsEnum_crcViolationDrivingPermission	= 4,
	Vanetza_ITS2_SafetyViolationsEnum_expirationTimeViolation	= 5,
	Vanetza_ITS2_SafetyViolationsEnum_drivingDirectionMismatch	= 6,
	Vanetza_ITS2_SafetyViolationsEnum_velocityViolation	= 7,
	Vanetza_ITS2_SafetyViolationsEnum_curvatureMinViolation	= 8,
	Vanetza_ITS2_SafetyViolationsEnum_curvatureMaxViolation	= 9,
	Vanetza_ITS2_SafetyViolationsEnum_expirationTimeTooHigh	= 10,
	Vanetza_ITS2_SafetyViolationsEnum_monitoring	= 11
	/*
	 * Enumeration is extensible
	 */
} e_Vanetza_ITS2_SafetyViolationsEnum;

/* Vanetza_ITS2_SafetyViolationsEnum */
typedef long	 Vanetza_ITS2_SafetyViolationsEnum_t;

/* Implementation */
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_SafetyViolationsEnum_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_SafetyViolationsEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_SafetyViolationsEnum;
extern const asn_INTEGER_specifics_t asn_SPC_Vanetza_ITS2_SafetyViolationsEnum_specs_1;
asn_struct_free_f Vanetza_ITS2_SafetyViolationsEnum_free;
asn_struct_print_f Vanetza_ITS2_SafetyViolationsEnum_print;
asn_constr_check_f Vanetza_ITS2_SafetyViolationsEnum_constraint;
ber_type_decoder_f Vanetza_ITS2_SafetyViolationsEnum_decode_ber;
der_type_encoder_f Vanetza_ITS2_SafetyViolationsEnum_encode_der;
xer_type_decoder_f Vanetza_ITS2_SafetyViolationsEnum_decode_xer;
xer_type_encoder_f Vanetza_ITS2_SafetyViolationsEnum_encode_xer;
jer_type_encoder_f Vanetza_ITS2_SafetyViolationsEnum_encode_jer;
oer_type_decoder_f Vanetza_ITS2_SafetyViolationsEnum_decode_oer;
oer_type_encoder_f Vanetza_ITS2_SafetyViolationsEnum_encode_oer;
per_type_decoder_f Vanetza_ITS2_SafetyViolationsEnum_decode_uper;
per_type_encoder_f Vanetza_ITS2_SafetyViolationsEnum_encode_uper;
per_type_decoder_f Vanetza_ITS2_SafetyViolationsEnum_decode_aper;
per_type_encoder_f Vanetza_ITS2_SafetyViolationsEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_SafetyViolationsEnum_H_ */
#include "asn_internal.h"
