/*
 * Generated by asn1c
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_SubmanoeuvreStrategy_H_
#define	_Vanetza_ITS2_SubmanoeuvreStrategy_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "NativeInteger.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_SubmanoeuvreStrategy_PR {
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_NOTHING,	/* No components present */
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_undefined,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_transitToHumanDrivenMode,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_transitToAutomatedDrivingMode,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_driveStraight,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_turnLeft,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_turnRight,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_uTurn,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_moveBackward,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_overtake,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_accelerate,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_slowDown,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_stop,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_goToLeftLane,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_goToRightLane,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_getOnHighway,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_exitHighway,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_takeTollingLane,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_stopAndWait,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_emergencyBrakeAndStop,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_resetStopAndRestartMoving,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_stayInLane,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_resetStayInLane,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_stayAway,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_resetStayAway,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_followMe,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_existingGroup,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_temporarilyDisbandAnExistingGroup,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_constituteATemporarilyGroup,
	Vanetza_ITS2_SubmanoeuvreStrategy_PR_disbandATemporarilyGroup
} Vanetza_ITS2_SubmanoeuvreStrategy_PR;

/* Vanetza_ITS2_SubmanoeuvreStrategy */
typedef struct Vanetza_ITS2_SubmanoeuvreStrategy {
	Vanetza_ITS2_SubmanoeuvreStrategy_PR present;
	union Vanetza_ITS2_SubmanoeuvreStrategy_u {
		NULL_t	 undefined;
		NULL_t	 transitToHumanDrivenMode;
		NULL_t	 transitToAutomatedDrivingMode;
		NULL_t	 driveStraight;
		NULL_t	 turnLeft;
		NULL_t	 turnRight;
		NULL_t	 uTurn;
		NULL_t	 moveBackward;
		NULL_t	 overtake;
		NULL_t	 accelerate;
		NULL_t	 slowDown;
		NULL_t	 stop;
		NULL_t	 goToLeftLane;
		NULL_t	 goToRightLane;
		NULL_t	 getOnHighway;
		NULL_t	 exitHighway;
		long	 takeTollingLane;
		NULL_t	 stopAndWait;
		NULL_t	 emergencyBrakeAndStop;
		NULL_t	 resetStopAndRestartMoving;
		NULL_t	 stayInLane;
		NULL_t	 resetStayInLane;
		NULL_t	 stayAway;
		NULL_t	 resetStayAway;
		NULL_t	 followMe;
		NULL_t	 existingGroup;
		NULL_t	 temporarilyDisbandAnExistingGroup;
		NULL_t	 constituteATemporarilyGroup;
		NULL_t	 disbandATemporarilyGroup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_SubmanoeuvreStrategy_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_SubmanoeuvreStrategy;
extern asn_CHOICE_specifics_t asn_SPC_Vanetza_ITS2_SubmanoeuvreStrategy_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_SubmanoeuvreStrategy_1[29];
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_SubmanoeuvreStrategy_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_SubmanoeuvreStrategy_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_SubmanoeuvreStrategy_H_ */
#include "asn_internal.h"
