/*
 * Generated by asn1c
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_SubmanoeuvreDescription_H_
#define	_Vanetza_ITS2_SubmanoeuvreDescription_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier1B.h"
#include "TemporalCharacteristics.h"
#include "KinematicsCharacteristics.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_SubmanoeuvreStrategy;
struct Vanetza_ITS2_Trajectory;
struct Vanetza_ITS2_TrrDescription;

/* Vanetza_ITS2_SubmanoeuvreDescription */
typedef struct Vanetza_ITS2_SubmanoeuvreDescription {
	Vanetza_ITS2_Identifier1B_t	 submanoeuvreID;
	struct Vanetza_ITS2_SubmanoeuvreStrategy	*submanoeuvreStrategy;	/* OPTIONAL */
	struct Vanetza_ITS2_Trajectory	*referenceTrajectory;	/* OPTIONAL */
	struct Vanetza_ITS2_TrrDescription	*targetRoadResourceIContainer;	/* OPTIONAL */
	Vanetza_ITS2_TemporalCharacteristics_t	 temporalCharateristics;
	Vanetza_ITS2_KinematicsCharacteristics_t	*kinematicsCharacteristics;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_SubmanoeuvreDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_SubmanoeuvreDescription;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_SubmanoeuvreDescription_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_SubmanoeuvreDescription_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SubmanoeuvreStrategy.h"
#include "Trajectory.h"
#include "TrrDescription.h"

#endif	/* _Vanetza_ITS2_SubmanoeuvreDescription_H_ */
#include "asn_internal.h"
