/*
 * Generated by asn1c
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "MIM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#include "TerminateReasonEnum.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_TerminateReasonEnum_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_Vanetza_ITS2_TerminateReasonEnum_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_Vanetza_ITS2_TerminateReasonEnum_value2enum_1[] = {
	{ 0,	7,	"proceed" },
	{ 1,	18,	"destinationReached" },
	{ 2,	19,	"infrastructureError" },
	{ 3,	12,	"vehicleError" },
	{ 4,	7,	"backend" },
	{ 5,	26,	"vehicleIdentificationError" }
};
static int asn_validate_Vanetza_ITS2_TerminateReasonEnum(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_Vanetza_ITS2_TerminateReasonEnum value = *(e_Vanetza_ITS2_TerminateReasonEnum*)sptr;
    switch(value) {
    case Vanetza_ITS2_TerminateReasonEnum_proceed:
    case Vanetza_ITS2_TerminateReasonEnum_destinationReached:
    case Vanetza_ITS2_TerminateReasonEnum_infrastructureError:
    case Vanetza_ITS2_TerminateReasonEnum_vehicleError:
    case Vanetza_ITS2_TerminateReasonEnum_backend:
    case Vanetza_ITS2_TerminateReasonEnum_vehicleIdentificationError:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_Vanetza_ITS2_TerminateReasonEnum_enum2value_1[] = {
	4,	/* backend(4) */
	1,	/* destinationReached(1) */
	2,	/* infrastructureError(2) */
	0,	/* proceed(0) */
	3,	/* vehicleError(3) */
	5	/* vehicleIdentificationError(5) */
};
const asn_INTEGER_specifics_t asn_SPC_Vanetza_ITS2_TerminateReasonEnum_specs_1 = {
	asn_MAP_Vanetza_ITS2_TerminateReasonEnum_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_Vanetza_ITS2_TerminateReasonEnum_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_Vanetza_ITS2_TerminateReasonEnum_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_TerminateReasonEnum = {
	"TerminateReasonEnum",
	"TerminateReasonEnum",
	&asn_OP_NativeEnumerated,
	asn_DEF_Vanetza_ITS2_TerminateReasonEnum_tags_1,
	sizeof(asn_DEF_Vanetza_ITS2_TerminateReasonEnum_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_TerminateReasonEnum_tags_1[0]), /* 1 */
	asn_DEF_Vanetza_ITS2_TerminateReasonEnum_tags_1,	/* Same as above */
	sizeof(asn_DEF_Vanetza_ITS2_TerminateReasonEnum_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_TerminateReasonEnum_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_Vanetza_ITS2_TerminateReasonEnum_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_Vanetza_ITS2_TerminateReasonEnum_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_Vanetza_ITS2_TerminateReasonEnum
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_Vanetza_ITS2_TerminateReasonEnum_specs_1	/* Additional specs */
};

