/*
 * Generated by asn1c
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_TerminationContainer_H_
#define	_Vanetza_ITS2_TerminationContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_ITS2_TerminationContainer */
typedef struct Vanetza_ITS2_TerminationContainer {
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_TerminationContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_TerminationContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_TerminationContainer_specs_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_TerminationContainer_H_ */
#include "asn_internal.h"
