/*
 * Generated by asn1c
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_TrrDescription_H_
#define	_Vanetza_ITS2_TrrDescription_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TrrType.h"
#include "LaneCount.h"
#include "TRRWidth.h"
#include "TRRLength.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_MCM_PDU_Descriptions_WayPoint;
struct Vanetza_ITS2_Wgs84Angle;

/* Vanetza_ITS2_TrrDescription */
typedef struct Vanetza_ITS2_TrrDescription {
	Vanetza_ITS2_TrrType_t	 trrType;
	Vanetza_ITS2_LaneCount_t	 laneCount;
	Vanetza_ITS2_LaneCount_t	*startingLaneNumber;	/* OPTIONAL */
	Vanetza_ITS2_LaneCount_t	*endingLaneNumber;	/* OPTIONAL */
	struct Vanetza_ITS2_TrrDescription__waypoints {
		A_SEQUENCE_OF(struct Vanetza_ITS2_WayPoint) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *waypoints;
	struct Vanetza_ITS2_TrrDescription__heading {
		A_SEQUENCE_OF(struct Vanetza_ITS2_Wgs84Angle) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *heading;
	Vanetza_ITS2_TRRWidth_t	 trrWidth;
	Vanetza_ITS2_TRRLength_t	 trrLength;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_TrrDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_TrrDescription;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_TrrDescription_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_TrrDescription_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MCM-PDU-Descriptions_WayPoint.h"
#include "Wgs84Angle.h"

#endif	/* _Vanetza_ITS2_TrrDescription_H_ */
#include "asn_internal.h"
