/*
 * Generated by asn1c
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_TrrType_H_
#define	_Vanetza_ITS2_TrrType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_TrrType {
	Vanetza_ITS2_TrrType_trrType1	= 0,
	Vanetza_ITS2_TrrType_trrType2	= 1,
	Vanetza_ITS2_TrrType_trrType3	= 2
} e_Vanetza_ITS2_TrrType;

/* Vanetza_ITS2_TrrType */
typedef long	 Vanetza_ITS2_TrrType_t;

/* Implementation */
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_TrrType_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_TrrType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_TrrType;
extern const asn_INTEGER_specifics_t asn_SPC_Vanetza_ITS2_TrrType_specs_1;
asn_struct_free_f Vanetza_ITS2_TrrType_free;
asn_struct_print_f Vanetza_ITS2_TrrType_print;
asn_constr_check_f Vanetza_ITS2_TrrType_constraint;
ber_type_decoder_f Vanetza_ITS2_TrrType_decode_ber;
der_type_encoder_f Vanetza_ITS2_TrrType_encode_der;
xer_type_decoder_f Vanetza_ITS2_TrrType_decode_xer;
xer_type_encoder_f Vanetza_ITS2_TrrType_encode_xer;
jer_type_encoder_f Vanetza_ITS2_TrrType_encode_jer;
oer_type_decoder_f Vanetza_ITS2_TrrType_decode_oer;
oer_type_encoder_f Vanetza_ITS2_TrrType_encode_oer;
per_type_decoder_f Vanetza_ITS2_TrrType_decode_uper;
per_type_encoder_f Vanetza_ITS2_TrrType_encode_uper;
per_type_decoder_f Vanetza_ITS2_TrrType_decode_aper;
per_type_encoder_f Vanetza_ITS2_TrrType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_TrrType_H_ */
#include "asn_internal.h"
