/*
 * Generated by asn1c
 * From ASN.1 module "MVM-PDU-Descriptions"
 * 	found in "MVM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_VehCodeEnum_H_
#define	_Vanetza_ITS2_VehCodeEnum_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_VehCodeEnum {
	Vanetza_ITS2_VehCodeEnum_unspecified	= 0,
	Vanetza_ITS2_VehCodeEnum_pathNotDriveable	= 1,
	Vanetza_ITS2_VehCodeEnum_onboardVehicleFault	= 2,
	Vanetza_ITS2_VehCodeEnum_communicationFault	= 3,
	Vanetza_ITS2_VehCodeEnum_vehicleEgressFault	= 4
	/*
	 * Enumeration is extensible
	 */
} e_Vanetza_ITS2_VehCodeEnum;

/* Vanetza_ITS2_VehCodeEnum */
typedef long	 Vanetza_ITS2_VehCodeEnum_t;

/* Implementation */
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_VehCodeEnum_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_VehCodeEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_VehCodeEnum;
extern const asn_INTEGER_specifics_t asn_SPC_Vanetza_ITS2_VehCodeEnum_specs_1;
asn_struct_free_f Vanetza_ITS2_VehCodeEnum_free;
asn_struct_print_f Vanetza_ITS2_VehCodeEnum_print;
asn_constr_check_f Vanetza_ITS2_VehCodeEnum_constraint;
ber_type_decoder_f Vanetza_ITS2_VehCodeEnum_decode_ber;
der_type_encoder_f Vanetza_ITS2_VehCodeEnum_encode_der;
xer_type_decoder_f Vanetza_ITS2_VehCodeEnum_decode_xer;
xer_type_encoder_f Vanetza_ITS2_VehCodeEnum_encode_xer;
jer_type_encoder_f Vanetza_ITS2_VehCodeEnum_encode_jer;
oer_type_decoder_f Vanetza_ITS2_VehCodeEnum_decode_oer;
oer_type_encoder_f Vanetza_ITS2_VehCodeEnum_encode_oer;
per_type_decoder_f Vanetza_ITS2_VehCodeEnum_decode_uper;
per_type_encoder_f Vanetza_ITS2_VehCodeEnum_encode_uper;
per_type_decoder_f Vanetza_ITS2_VehCodeEnum_decode_aper;
per_type_encoder_f Vanetza_ITS2_VehCodeEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_VehCodeEnum_H_ */
#include "asn_internal.h"
