/*
 * Generated by asn1c
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_VehicleCurrentStateContainer_H_
#define	_Vanetza_ITS2_VehicleCurrentStateContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Speed.h"
#include "Wgs84Angle.h"
#include "VehicleSize.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Vanetza_ITS2_ManoeuvreOverallStrategy;

/* Vanetza_ITS2_VehicleCurrentStateContainer */
typedef struct Vanetza_ITS2_VehicleCurrentStateContainer {
	struct Vanetza_ITS2_ManoeuvreOverallStrategy	*manoeuvreOverallStrategy;	/* OPTIONAL */
	Vanetza_ITS2_Speed_t	 vehicleSpeed;
	Vanetza_ITS2_Wgs84Angle_t	 vehicleHeading;
	Vanetza_ITS2_VehicleSize_t	 vehicleSize;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_VehicleCurrentStateContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_VehicleCurrentStateContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_VehicleCurrentStateContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_VehicleCurrentStateContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ManoeuvreOverallStrategy.h"

#endif	/* _Vanetza_ITS2_VehicleCurrentStateContainer_H_ */
#include "asn_internal.h"
