/*
 * Generated by asn1c
 * From ASN.1 module "LHP-PMM-PDU-Descriptions"
 * 	found in "LHP-PMM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_VlAssignment_H_
#define	_Vanetza_ITS2_VlAssignment_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AssignedStationList.h"
#include "ClusterID.h"
#include "BOOLEAN.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_ITS2_VlAssignment */
typedef struct Vanetza_ITS2_VlAssignment {
	Vanetza_ITS2_AssignedStationList_t	 assignedStations;
	Vanetza_ITS2_ClusterID_t	 clusterId;
	BOOLEAN_t	 vlIndicator;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_ITS2_VlAssignment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_VlAssignment;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_VlAssignment_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_ITS2_VlAssignment_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_VlAssignment_H_ */
#include "asn_internal.h"
