/*
 * Generated by asn1c
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fcomplex-threshold=500 -fprefix=Vanetza_ITS2_ -R`
 */

#include "WrappedExtensionContainer.h"

#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_containerData __attribute__((weak, alias("asn_DEF_Vanetza_ITS2_containerData_3")));
#else
static asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_containerData_3;
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_containerData;
__attribute__((constructor)) static void asn_DEF_Vanetza_ITS2_containerData_3_alias_init(void) {
	asn_DEF_Vanetza_ITS2_containerData = asn_DEF_Vanetza_ITS2_containerData_3;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_containerData_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_Vanetza_ITS2_containerData_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_Vanetza_ITS2_containerData_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData, choice.lhpContainer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_LhpContainer,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"lhpContainer"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Vanetza_ITS2_containerData_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* lhpContainer */
};
static asn_CHOICE_specifics_t asn_SPC_Vanetza_ITS2_containerData_specs_3 = {
	sizeof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData),
	offsetof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData, _asn_ctx),
	offsetof(struct Vanetza_ITS2_WrappedExtensionContainer__containerData, present),
	sizeof(((struct Vanetza_ITS2_WrappedExtensionContainer__containerData *)0)->present),
	asn_MAP_Vanetza_ITS2_containerData_tag2el_3,
	1,	/* Count of tags in the map */
	0, 0,
	1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_containerData_3 = {
	"containerData",
	"containerData",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_Vanetza_ITS2_containerData_constr_3,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_Vanetza_ITS2_containerData_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_Vanetza_ITS2_containerData_3,
	1,	/* Elements count */
	&asn_SPC_Vanetza_ITS2_containerData_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Vanetza_ITS2_WrappedExtensionContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_WrappedExtensionContainer, containerId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"containerId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_WrappedExtensionContainer, containerData),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_containerData,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"containerData"
		},
};
static const ber_tlv_tag_t asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Vanetza_ITS2_WrappedExtensionContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* containerId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* containerData */
};
asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_WrappedExtensionContainer_specs_1 = {
	sizeof(struct Vanetza_ITS2_WrappedExtensionContainer),
	offsetof(struct Vanetza_ITS2_WrappedExtensionContainer, _asn_ctx),
	asn_MAP_Vanetza_ITS2_WrappedExtensionContainer_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_WrappedExtensionContainer = {
	"WrappedExtensionContainer",
	"WrappedExtensionContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1,
	sizeof(asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1[0]), /* 1 */
	asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_WrappedExtensionContainer_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Vanetza_ITS2_WrappedExtensionContainer_1,
	2,	/* Elements count */
	&asn_SPC_Vanetza_ITS2_WrappedExtensionContainer_specs_1	/* Additional specs */
};

